import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import type { Plugin } from "vitest/config";

// Directories under the repo root that hold workspace packages whose
// `exports` map a public name onto built `dist/`. Mirrors the non-glob
// prefixes of `pnpm-workspace.yaml`'s `packages:` list; nested playgrounds
// are private and never imported by name, so they're skipped.
const PACKAGE_ROOTS = ["packages", "packages/plugins", "packages/runtimes"];

const REPO_ROOT = fileURLToPath(new URL("../../", import.meta.url));

// Compiled i18n catalogs (`locales/*.mjs`) are generated by `i18n:compile` and
// have no source form. Resolving name-imported ones to an empty stub lets
// `test` skip that step; see `empty-catalog.ts` for why that's safe.
const EMPTY_CATALOG = fileURLToPath(
  new URL("./empty-catalog.ts", import.meta.url),
);

interface WorkspacePackage {
  readonly dir: string;
  readonly exports: Record<string, unknown>;
}

function loadWorkspacePackages(): Map<string, WorkspacePackage> {
  const map = new Map<string, WorkspacePackage>();
  for (const root of PACKAGE_ROOTS) {
    const base = join(REPO_ROOT, root);
    if (!existsSync(base)) continue;
    for (const entry of readdirSync(base, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const dir = join(base, entry.name);
      const manifest = join(dir, "package.json");
      if (!existsSync(manifest)) continue;
      const pkg = JSON.parse(readFileSync(manifest, "utf8")) as {
        name?: string;
        exports?: Record<string, unknown>;
      };
      if (pkg.name && pkg.exports)
        map.set(pkg.name, { dir, exports: pkg.exports });
    }
  }
  return map;
}

// The dist target an export condition points at (`./dist/plugin/manifest.js`).
// Take the runtime condition; the `source` we want is derived from it.
function distTarget(entry: unknown): string | null {
  if (typeof entry === "string") return entry;
  if (entry && typeof entry === "object") {
    const conditions = entry as Record<string, unknown>;
    for (const key of ["import", "default", "node", "types"]) {
      const value = conditions[key];
      if (typeof value === "string") return value;
    }
  }
  return null;
}

// `./dist/plugin/manifest.js` → the `src` file that builds it. The tsc build is
// 1:1 (`src/**/*.ts` → `dist/**/*.js`), so swap the segment and try each source
// extension.
function sourceCandidate(dir: string, target: string): string | null {
  if (!target.includes("/dist/")) return null;
  const stripped = target
    .replace("/dist/", "/src/")
    .replace(/\.(js|mjs|cjs|d\.ts|d\.mts)$/, "");
  for (const ext of [".ts", ".tsx", ".mts", "/index.ts", "/index.tsx"]) {
    const candidate = join(dir, stripped + ext);
    if (existsSync(candidate)) return candidate;
  }
  return null;
}

function splitSpecifier(
  source: string,
): { name: string; subpath: string } | null {
  if (source.startsWith("@")) {
    const parts = source.split("/");
    if (parts.length < 2) return null;
    const name = `${parts[0]}/${parts[1]}`;
    const rest = parts.slice(2).join("/");
    return { name, subpath: rest ? `./${rest}` : "." };
  }
  const [name, ...rest] = source.split("/");
  if (!name) return null;
  return { name, subpath: rest.length ? `./${rest.join("/")}` : "." };
}

function matchExport(
  exports: Record<string, unknown>,
  subpath: string,
): { entry: unknown; star?: string } | null {
  if (subpath in exports) return { entry: exports[subpath] };
  for (const [key, entry] of Object.entries(exports)) {
    const star = key.indexOf("*");
    if (star === -1) continue;
    const prefix = key.slice(0, star);
    const suffix = key.slice(star + 1);
    if (subpath.startsWith(prefix) && subpath.endsWith(suffix)) {
      return {
        entry,
        star: subpath.slice(prefix.length, subpath.length - suffix.length),
      };
    }
  }
  return null;
}

/**
 * Resolves `@plumix/*` / `plumix` workspace imports to their `src/` entry
 * during vitest, so unit tests exercise source and don't depend on a build.
 * The `src` path is derived from each package's own `exports` map (dist → src),
 * so it can't drift from the published surface the way a hand-kept alias list
 * would. Name-imported compiled `locales/*` catalogs resolve to an empty stub
 * (generated, no source form). Anything else without a matching source file
 * falls through to normal resolution untouched. (The vendor `plumix/admin/*`
 * shims do map to source, but no unit test imports them, so the single-React
 * runtime indirection is never exercised here.)
 *
 * This rewrites Vite's module graph only. `require.resolve` / `fs` reads at
 * test runtime still hit `dist`, so a package whose tests reach a build
 * artifact that way keeps a `build` dep in its own turbo.json (see plumix).
 */
export function plumixSourceResolver(): Plugin {
  const packages = loadWorkspacePackages();
  return {
    name: "plumix:source-resolver",
    enforce: "pre",
    resolveId(source) {
      const split = splitSpecifier(source);
      if (!split) return null;
      const pkg = packages.get(split.name);
      if (!pkg) return null;
      const matched = matchExport(pkg.exports, split.subpath);
      if (!matched) return null;
      let target = distTarget(matched.entry);
      if (!target) return null;
      if (matched.star !== undefined)
        target = target.replaceAll("*", matched.star);
      if (target.includes("/locales/")) return EMPTY_CATALOG;
      return sourceCandidate(pkg.dir, target);
    },
  };
}
