import type { EntrySourceOptions } from "plumix";

/** The module-worker entry: `export default { fetch, scheduled }`. */
export function generateEntry({ configModule }: EntrySourceOptions): string {
  const lines = [
    "// Generated by plumix — do not edit.",
    "// Regenerated from plumix.config.ts on each build.",
    "",
    'import { buildApp, renderDevBootErrorResponse } from "plumix";',
    // The plumix Vite plugin resolves this virtual module — in dev it's
    // `{}`; in build it's the parsed `.vite/manifest.json` Vite emitted
    // for the client environment. The SSR renderer reads it to inject
    // hashed `<link rel="stylesheet">` tags after the theme's `link[]`.
    'import assetManifest from "virtual:plumix/asset-manifest";',
    `import config from ${JSON.stringify(configModule)};`,
    "",
    // Re-export named worker-level exports (e.g. Durable Object classes)
    // that config slots contribute. The plumix Vite plugin resolves this
    // virtual module from `runtime.workerExports`; it's an empty module
    // when nothing is contributed, so this line is inert for most sites.
    'export * from "virtual:plumix/worker-exports";',
    "",
    // buildApp derives the dev-CSRF opt-in from `process.env.PLUMIX_DEV` (the
    // single dev signal the plumix Vite plugin statically replaces), so the
    // worker no longer passes it — see RuntimeContext.devCsrfLocalhost.
    "const appPromise = buildApp(config, {",
    "  assetManifest,",
    "});",
    "let handler;",
    "",
    // The handler contract is runtime-neutral: a `Request` plus one invocation.
    // This is the only place that knows the Worker's positional `(env, ctx)`.
    "const invocation = (env, ctx) => ({ env, waitUntil: (promise) => ctx.waitUntil(promise) });",
    "",
    "export default {",
    "  async fetch(request, env, ctx) {",
    "    let app;",
    "    try {",
    "      app = await appPromise;",
    "    } catch (bootError) {",
    // Dev-only: app construction failed (invalid theme registration, plugin
    // setup error, …). Serve the dev error page — with the typed error's hint —
    // for every request instead of an opaque crash. The gate is statically
    // false in prod, so this collapses to `throw bootError;` and the branch (and
    // the imported renderer) tree-shake out — production's boot path is
    // unchanged (#1601).
    "      if (process.env.PLUMIX_DEV) {",
    "        return renderDevBootErrorResponse(bootError);",
    "      }",
    "      throw bootError;",
    "    }",
    "    handler ??= config.runtime.createHandler(app);",
    "    return handler.fetch(request, invocation(env, ctx));",
    "  },",
    "  async scheduled(event, env, ctx) {",
    "    const app = await appPromise;",
    "    handler ??= config.runtime.createHandler(app);",
    "    if (handler.scheduled) await handler.scheduled(event, invocation(env, ctx));",
    "  },",
    "};",
    "",
  ];
  return lines.join("\n");
}
