import type { EntrySourceOptions } from "plumix";

/** The module-worker entry: `export default { fetch, scheduled }`. */
export function generateEntry({ configModule }: EntrySourceOptions): string {
  const lines = [
    "// Generated by plumix — do not edit.",
    "// Regenerated from plumix.config.ts on each build.",
    "",
    'import { buildApp, createRuntimeHandler, renderDevBootErrorResponse } from "plumix/runtime";',
    // Imported rather than spelled out: string-literal code is unreachable to
    // the compiler, linter and tests.
    'import { surfaceScheduledFailure } from "@plumix/runtime-cloudflare";',
    // `{}` in dev; in build, the client environment's parsed
    // `.vite/manifest.json`.
    'import assetManifest from "virtual:plumix/asset-manifest";',
    // Each plugin's compiled catalogs by locale, lazy-imported, so SSR block
    // renders resolve plugin strings for the request locale.
    'import pluginCatalogs from "virtual:plumix/plugin-catalogs";',
    `import config from ${JSON.stringify(configModule)};`,
    "",
    // Empty when no config slot contributes a worker export, such as a Durable
    // Object class.
    'export * from "virtual:plumix/worker-exports";',
    "",
    // buildApp derives its dev object from `process.env.PLUMIX_DEV` (the
    // single dev signal the plumix Vite plugin statically replaces), so the
    // worker passes no dev flag.
    "const appPromise = buildApp(config, {",
    "  assetManifest,",
    "  pluginCatalogs,",
    "});",
    "let handler;",
    "",
    // The handler contract is runtime-neutral: a `Request` plus one invocation.
    // This is the only place that knows the Worker's positional `(env, ctx)`.
    "const invocation = (env, ctx) => ({ env, waitUntil: (promise) => ctx.waitUntil(promise) });",
    "",
    "export default {",
    "  async fetch(request, env, ctx) {",
    "    let app;",
    "    try {",
    "      app = await appPromise;",
    "    } catch (bootError) {",
    // Statically false in production, so this collapses to `throw bootError;`
    // and the renderer tree-shakes out.
    "      if (process.env.PLUMIX_DEV) {",
    "        return renderDevBootErrorResponse(bootError);",
    "      }",
    "      throw bootError;",
    "    }",
    "    handler ??= createRuntimeHandler(app);",
    "    return handler.fetch(request, invocation(env, ctx));",
    "  },",
    "  async scheduled(event, env, ctx) {",
    "    const app = await appPromise;",
    "    handler ??= createRuntimeHandler(app);",
    // `?.` rather than a guard: an adapter with no `scheduled` reports
    // nothing, and a report of nothing fails nothing (#2361).
    "    const report = await handler.scheduled?.(event, invocation(env, ctx));",
    "    surfaceScheduledFailure(report, event);",
    "  },",
    "};",
    "",
  ];
  return lines.join("\n");
}
