packages:
  - "packages/*"
  - "packages/runtimes/*"
  - "packages/plugins/*"
  - "examples/*"
  - "tooling/*"

catalog:
  "@arethetypeswrong/cli": ^0.18.2
  "@cloudflare/workers-types": ^4.20260417.1
  "@types/node": ^24.12.2
  "drizzle-kit": ^0.31.10
  "drizzle-orm": ^0.45.2
  "drizzle-valibot": ^0.4.2
  eslint: ^9.39.4
  prettier: ^3.8.3
  publint: ^0.3.18
  typescript: ^6.0.3
  valibot: ^1.3.1
  vite: ^8.0.8
  vitest: ^4.1.4

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss

overrides:
  "esbuild@<0.25.0": ">=0.25.0"
