// What a plugin writes against, plus valibot for its RPC inputs. The types
// are its own role's; the root carries every type too, for the declaration
// emitter (see `./index.ts`).
export * as v from "valibot";

// Definition, RPC, hooks, the registries a plugin reads, and the harness its
// own tests assemble an app from. Prefer `canEditEntry` / `assertCanEditEntry`
// to a hand-built `entry:<type>:edit_any`, which misses the namespace a pooled
// type gates under; `requireCapability` still covers row-independent checks.
export {
  assertCanEditEntry,
  authenticated,
  base,
  buildManifest,
  canEditEntry,
  createAppContext,
  createPluginRegistry,
  DEFAULT_HOOK_PRIORITY,
  definePlugin,
  ENTRY_MENU_ICONS,
  findEntryMetaField,
  findTermMetaField,
  findUserMetaField,
  HookRegistry,
  imageRoleFields,
  installPlugins,
  listEntryMetaFields,
  listTermMetaFields,
  listUserMetaFields,
  McpToolError,
  memoBatch,
  PLUGIN_I18N_SLOT,
  pluginAdminEntryPath,
  previewableEntry,
  projectImageRoles,
  registerCoreLookupAdapters,
  requireCapability,
  TAXONOMY_MENU_ICONS,
} from "@plumix/core";

// `tryGetContext` serves a component rendered without a context argument, such
// as SEO's breadcrumbs; `requestStore` is kept with it so a test can enter the
// scope that reader looks in.
export { requestStore, tryGetContext } from "@plumix/core";

// Entries, routing, the URL space and what a page says about itself.
export {
  ackEntryChanges,
  adminEntryScope,
  archiveAtPath,
  archiveBaseRoutes,
  archiveSlugForEntryType,
  buildEntryPermalink,
  archiveRoutes,
  buildEntryPermalinks,
  buildTermArchiveUrl,
  buildTermArchiveUrls,
  canonicalUrl,
  dateRange,
  entryGroups,
  exposesHierarchicalUrls,
  findTermByPath,
  FRAMEWORK_PAGINATION_SUFFIX,
  FRAMEWORK_SEARCH_PAGINATED_PATTERN,
  FRAMEWORK_SEARCH_QUERY_PATTERN,
  getAutosave,
  isCurrentSource,
  loadSettingsGroups,
  loadSiteSettings,
  readEntryChanges,
  readEntryType,
  resolveImageRoles,
  resolveReferences,
  termTaxonomyBaseSlug,
} from "@plumix/core";

// A rule kind of the plugin's own, resolved through the same walk a theme's
// templates are, and the template machinery a plugin rendering on a theme's
// behalf reads.
export {
  archiveTypeTargets,
  authorTargets,
  buildResolvedEntries,
  dateTargets,
  entryTypeMatch,
  entryTypeTargets,
  loadTemplateDeps,
  metaEquals,
  pageFacts,
  resolveErrorRule,
  resolveErrorTemplate,
  resolveListingPage,
  resolveRule,
  resolveTemplate,
  ruleLabel,
  termMetaEquals,
  termTaxonomyMatch,
  termTaxonomyTargets,
} from "@plumix/core";

// Responses a plugin route answers with, and the CDN tag it stores one under.
export {
  forbidden,
  jsonResponse,
  methodNotAllowed,
  notFoundResponse,
  serveRenderedAsset,
  tagCdnEntry,
} from "@plumix/core";

// Dev surfaces a plugin contributes panels to.
export {
  DebugKV,
  DebugSection,
  DevErrorEmptyNote,
  DevErrorFacts,
  DevErrorSubhead,
} from "@plumix/core";

export type {
  AccessPolicyChoice,
  ActionArgs,
  ActionFn,
  ActionName,
  AdminEntryGroup,
  AdminEntryScope,
  AdminNavGroup,
  AdminNavGroupRef,
  AdminNavItem,
  AdminPageOptions,
  AdminSearchInput,
  AppContext,
  AppContextBase,
  ArchiveAtPath,
  ArchiveBaseRoute,
  ArchiveEntries,
  ArchiveTitle,
  ArchiveTypeDeclaration,
  AuthenticatedAppContext,
  AuthenticatedUser,
  AuthNamespace,
  AuthorTargets,
  AutosavePairInput,
  Base,
  BindRule,
  BlockLoaderErrorContext,
  BlockManifestEntry,
  BlockRenderHookContext,
  BuiltManifest,
  ContextExtensionEntry,
  CoreIconName,
  CoreSchema,
  CreateAppContextArgs,
  CurrentSource,
  CustomArchiveResolution,
  DashboardWidgetManifestEntry,
  DashboardWidgetOptions,
  DateTargets,
  Db,
  DebugKVRow,
  DebugPanel,
  DeferFn,
  DefinePluginInput,
  DefinePluginOptions,
  DevErrorFact,
  DevErrorHint,
  DevErrorHintDoc,
  DevErrorPanel,
  EntryArchive,
  EntryChange,
  EntryEditErrors,
  EntryListing,
  EntryMenuIcon,
  EntryMeta,
  EntryMetaBoxFieldManifestEntry,
  EntryMetaBoxManifestEntry,
  EntryMetaBoxOptions,
  EntryReferenceSummary,
  EntryTypeAccess,
  EntryTypeLabels,
  EntryTypeManifestEntry,
  EntryTypeTargets,
  FieldTypeManifestEntry,
  FieldTypeOptions,
  FilterFn,
  FilterInput,
  FilterName,
  FilterRest,
  GenericTier,
  HookExecutor,
  HookOptions,
  HookRegistryOptions,
  HydratedReference,
  I18nManifest,
  ImageRoleField,
  ImageRoleName,
  ImageRoleOptions,
  ImageRoleScope,
  InferFields,
  InferStoredFields,
  ListingArchiveResolution,
  ListingPageTarget,
  Logger,
  LoginLinkOptions,
  LogMeta,
  LookupAdapter,
  LookupHydrateOptions,
  LookupListOptions,
  LookupResult,
  MarkManifestEntry,
  MatchedEntry,
  MatchNarrowing,
  McpTool,
  MetaBoxBaseManifestEntry,
  MetaBoxBaseOptions,
  MetaOf,
  MetaStore,
  MetaSweep,
  MutablePluginRegistry,
  NamedTemplateChoice,
  OgImage,
  PageFacts,
  PatternManifestEntry,
  PluginAfterSetup,
  PluginAfterSetupContext,
  PluginComponentRef,
  PluginDescriptor,
  PluginI18nManifest,
  PluginI18nSlot,
  PluginInstallResult,
  PluginProvides,
  PluginProvidesContext,
  PluginRegistry,
  PluginRouteAuth,
  PluginRouteMethod,
  PluginRpcRouter,
  PluginSetup,
  PluginSetupContext,
  PluginSetupContextBase,
  PlumixManifest,
  ProjectImageRolesOptions,
  PublicRouteOptions,
  RawSqlMigration,
  RedirectResolution,
  RedirectRule,
  RedirectStatus,
  RedirectTarget,
  RegisteredAdminPage,
  RegisteredArchiveType,
  RegisteredBlock,
  RegisteredCapability,
  RegisteredDashboardWidget,
  RegisteredEntryMetaBox,
  RegisteredEntryType,
  RegisteredFieldType,
  RegisteredImageRole,
  RegisteredLoginLink,
  RegisteredLookupAdapter,
  RegisteredMark,
  RegisteredMcpTool,
  RegisteredPattern,
  RegisteredPublicRoute,
  RegisteredRawRoute,
  RegisteredRestResource,
  RegisteredRewriteRule,
  RegisteredScheduledTask,
  RegisteredSettingsGroup,
  RegisteredSettingsPage,
  RegisteredShortcode,
  RegisteredTermMetaBox,
  RegisteredTermTaxonomy,
  RegisteredUserMetaBox,
  RenderedAssetArgs,
  RequestMemo,
  ResolvedEntity,
  ResolvedImage,
  ResolvedListingPage,
  ResolvedMeta,
  ResolvedNode,
  ResolvedRoute,
  RestResourceAuth,
  RestResourceMethod,
  RestResourceOptions,
  RoleImages,
  RouteIntent,
  RouteRule,
  ScheduledTask,
  SchemaSource,
  SearchGroup,
  SearchResultItem,
  SelectableAccessPolicy,
  SettingsGroupManifestEntry,
  SettingsGroupOptions,
  SettingsMeta,
  SettingsOf,
  SettingsPageManifestEntry,
  SettingsPageOptions,
  StoredMeta,
  StoredMetaOf,
  StoredTermMetaOf,
  TargetMatcher,
  TaxonomyMenuIcon,
  TermMeta,
  TermMetaBoxManifestEntry,
  TermMetaBoxOptions,
  TermMetaOf,
  TermReferenceSummary,
  TermTaxonomyLabels,
  TermTaxonomyManifestEntry,
  TermTaxonomyTargets,
  TierMatchRule,
  TitledListingArchiveResolution,
  UnsettledKeyCount,
  UserMeta,
  UserMetaBoxManifestEntry,
  UserMetaBoxOptions,
  UserMetaOf,
  UserReferenceSummary,
  WithResolvedMeta,
} from "@plumix/core";
