import { defineConfig } from "eslint/config";

import { baseConfig } from "@plumix/eslint-config/base";

export default defineConfig(
  // Astro's generated type output, regenerated by `astro sync` before lint.
  { ignores: [".astro/**"] },
  baseConfig,
  {
    // Astro's ambient env file references generated types by path — the one
    // sanctioned triple-slash reference in the project.
    files: ["src/env.d.ts"],
    rules: { "@typescript-eslint/triple-slash-reference": "off" },
  },
);
