import { describe, expect, test } from "vitest";

import type { PlumixConfig } from "../config.js";
import type { PluginDescriptor } from "../plugin/define.js";
import { generateSchemaSource } from "./schema-codegen.js";

const baseConfig: PlumixConfig = {
  runtime: { name: "test", buildFetchHandler: () => () => new Response() },
  database: { kind: "test", connect: () => ({ db: {} }) },
  auth: {
    passkey: { rpName: "t", rpId: "t", origin: "https://t" },
  },
  themes: [],
  plugins: [],
};

function pluginWithSchemaModule(
  id: string,
  schemaModule: string,
): PluginDescriptor {
  return {
    id,
    setup: () => undefined,
    schemaModule,
  };
}

describe("generateSchemaSource", () => {
  test("always re-exports plumix/schema first", () => {
    const { source, modules } = generateSchemaSource(baseConfig);
    expect(modules[0]).toBe("plumix/schema");
    expect(source).toContain('export * from "plumix/schema";');
  });

  test("appends each plugin's schemaModule after core", () => {
    const { source, modules } = generateSchemaSource({
      ...baseConfig,
      plugins: [
        pluginWithSchemaModule("blog", "@plumix/plugin-blog/schema"),
        pluginWithSchemaModule("pages", "@plumix/plugin-pages/schema"),
      ],
    });

    expect([...modules]).toEqual([
      "plumix/schema",
      "@plumix/plugin-blog/schema",
      "@plumix/plugin-pages/schema",
    ]);
    expect(source).toContain('export * from "@plumix/plugin-blog/schema";');
    expect(source).toContain('export * from "@plumix/plugin-pages/schema";');
  });

  test("deduplicates plugins that reference the same schema module", () => {
    const { modules } = generateSchemaSource({
      ...baseConfig,
      plugins: [
        pluginWithSchemaModule("a", "shared/schema"),
        pluginWithSchemaModule("b", "shared/schema"),
      ],
    });
    expect([...modules]).toEqual(["plumix/schema", "shared/schema"]);
  });

  test("emits a generated-file banner", () => {
    const { source } = generateSchemaSource(baseConfig);
    expect(source).toMatch(/^\/\/ Generated by plumix/);
  });
});
