import type { PlumixConfig } from "../config.js";

export const CORE_SCHEMA_MODULE = "plumix/schema";

export interface SchemaSource {
  readonly source: string;
  readonly modules: readonly string[];
}

export function generateSchemaSource(config: PlumixConfig): SchemaSource {
  const modules = [CORE_SCHEMA_MODULE];
  const seen = new Set<string>(modules);
  for (const plugin of config.plugins) {
    const spec = plugin.schemaModule;
    if (spec && !seen.has(spec)) {
      seen.add(spec);
      modules.push(spec);
    }
  }

  const lines = [
    "// Generated by plumix — do not edit.",
    "// Regenerated from plumix.config.ts on each build.",
    "",
    ...modules.map((spec) => `export * from ${JSON.stringify(spec)};`),
    "",
  ];
  return { source: lines.join("\n"), modules };
}
