export interface WorkerSourceOptions {
  readonly configModule: string;
}

export function generateWorkerSource({
  configModule,
}: WorkerSourceOptions): string {
  const lines = [
    "// Generated by plumix — do not edit.",
    "// Regenerated from plumix.config.ts on each build.",
    "",
    'import { buildApp } from "plumix";',
    // The plumix Vite plugin resolves this virtual module — in dev it's
    // `{}`; in build it's the parsed `.vite/manifest.json` Vite emitted
    // for the client environment. The SSR renderer reads it to inject
    // hashed `<link rel="stylesheet">` tags after the theme's `link[]`.
    'import assetManifest from "virtual:plumix/asset-manifest";',
    'import { islandManifest } from "virtual:plumix/island-manifest";',
    `import config from ${JSON.stringify(configModule)};`,
    "",
    "const appPromise = buildApp(config, { assetManifest, islandManifest });",
    "let fetchHandler;",
    "let scheduledHandler;",
    "",
    "export default {",
    "  async fetch(request, env, ctx) {",
    "    const app = await appPromise;",
    "    fetchHandler ??= config.runtime.buildFetchHandler(app);",
    "    return fetchHandler(request, env, ctx);",
    "  },",
    "  async scheduled(event, env, ctx) {",
    "    const app = await appPromise;",
    "    scheduledHandler ??= config.runtime.buildScheduledHandler?.(app);",
    "    if (scheduledHandler) await scheduledHandler(event, env, ctx);",
    "  },",
    "};",
    "",
  ];
  return lines.join("\n");
}
