export interface WorkerSourceOptions {
  readonly configModule: string;
}

export function generateWorkerSource({
  configModule,
}: WorkerSourceOptions): string {
  const lines = [
    "// Generated by plumix — do not edit.",
    "// Regenerated from plumix.config.ts on each build.",
    "",
    'import { buildApp } from "plumix";',
    // The plumix Vite plugin resolves this virtual module — in dev it's
    // `{}`; in build it's the parsed `.vite/manifest.json` Vite emitted
    // for the client environment. The SSR renderer reads it to inject
    // hashed `<link rel="stylesheet">` tags after the theme's `link[]`.
    'import assetManifest from "virtual:plumix/asset-manifest";',
    `import config from ${JSON.stringify(configModule)};`,
    "",
    // Re-export named worker-level exports (e.g. Durable Object classes)
    // that config slots contribute. The plumix Vite plugin resolves this
    // virtual module from `runtime.workerExports`; it's an empty module
    // when nothing is contributed, so this line is inert for most sites.
    'export * from "virtual:plumix/worker-exports";',
    "",
    // buildApp derives the dev-CSRF opt-in from `process.env.PLUMIX_DEV` (the
    // single dev signal the plumix Vite plugin statically replaces), so the
    // worker no longer passes it — see RuntimeContext.devCsrfLocalhost.
    "const appPromise = buildApp(config, {",
    "  assetManifest,",
    "});",
    "let fetchHandler;",
    "let scheduledHandler;",
    "",
    "export default {",
    "  async fetch(request, env, ctx) {",
    "    const app = await appPromise;",
    "    fetchHandler ??= config.runtime.buildFetchHandler(app);",
    "    return fetchHandler(request, env, ctx);",
    "  },",
    "  async scheduled(event, env, ctx) {",
    "    const app = await appPromise;",
    "    scheduledHandler ??= config.runtime.buildScheduledHandler?.(app);",
    "    if (scheduledHandler) await scheduledHandler(event, env, ctx);",
    "  },",
    "};",
    "",
  ];
  return lines.join("\n");
}
