import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { format, resolveConfig } from "prettier";

// Everything in `src/` is a component module unless it is the barrel itself
// or a test.
const BARREL = "index";

/**
 * The only hand-maintained part of the roster: a `src/` module left out of a
 * list it would otherwise be derived into, and why.
 */
interface RosterException {
  readonly omitFrom: "barrel";
  readonly reason: string;
}

const EXCEPTIONS: Readonly<Record<string, RosterException>> = {
  icons: {
    omitFrom: "barrel",
    reason:
      "`icons.ts` pairs `export *` from lucide with a runtime `blockIcons` " +
      "lookup, which defeats tree-shaking and pulls ~600 KB of lucide. " +
      "`plumix/admin/ui` stars the barrel wholesale, so barrelling it would " +
      "push `blockIcons` into every plugin chunk. The consequence: plugins " +
      "have no icon path at all — none uses one today, but the gap is real " +
      "and this is where a ticket giving them one starts.",
  },
};

interface ExportTarget {
  readonly types: string;
  readonly default: string;
}

interface Manifest {
  exports?: Readonly<Record<string, ExportTarget>>;
}

function componentModules(packageDir: string): string[] {
  return readdirSync(join(packageDir, "src"))
    .filter((file) => /\.tsx?$/.test(file) && !/\.test\.tsx?$/.test(file))
    .map((file) => file.replace(/\.tsx?$/, ""))
    .filter((name) => name !== BARREL)
    .sort((a, b) => a.localeCompare(b));
}

function target(name: string): ExportTarget {
  return { types: `./dist/${name}.d.ts`, default: `./dist/${name}.js` };
}

function expectedExports(modules: readonly string[]) {
  return Object.fromEntries([
    [".", target(BARREL)],
    ...modules.map((name) => [`./${name}`, target(name)] as const),
  ]);
}

function expectedBarrel(modules: readonly string[]): string {
  const lines = modules
    .filter((name) => EXCEPTIONS[name]?.omitFrom !== "barrel")
    .map((name) => `export * from "./${name}.js";`);
  return [
    "// Generated by `pnpm roster:sync` from the modules in `src/` and the",
    "// exception table in `scripts/roster.ts`. Don't edit by hand.",
    ...lines,
    "",
  ].join("\n");
}

function readManifest(packageDir: string): Manifest {
  return JSON.parse(
    readFileSync(join(packageDir, "package.json"), "utf8"),
  ) as Manifest;
}

const barrelPath = (packageDir: string) => join(packageDir, "src/index.ts");

function barrelModules(source: string): string[] {
  return [...source.matchAll(/export \* from "\.\/([^"]+)\.js";/g)].flatMap(
    (match) => (match[1] === undefined ? [] : [match[1]]),
  );
}

function listDrift(
  list: string,
  expected: readonly string[],
  actual: readonly string[],
  modules: readonly string[],
): string[] {
  return [
    ...expected
      .filter((name) => !actual.includes(name))
      .map((name) => `\`${name}\` is missing from ${list}`),
    ...actual
      .filter((name) => !modules.includes(name))
      .map((name) => `\`${name}\` is in ${list} but has no src/ module`),
    ...actual
      .filter((name) => modules.includes(name) && !expected.includes(name))
      .map(
        (name) =>
          `\`${name}\` is in ${list}, which its exception in scripts/roster.ts leaves it out of`,
      ),
  ];
}

/**
 * How the committed `exports` map and barrel differ from what `syncRoster`
 * would write, one line per module and stale list. Empty when in sync.
 */
export function rosterDrift(packageDir: string): string[] {
  const modules = componentModules(packageDir);
  const { exports } = readManifest(packageDir);
  const exportKeys = Object.keys(exports ?? {})
    .filter((key) => key !== ".")
    .map((key) => key.slice(2));
  const barrel = readFileSync(barrelPath(packageDir), "utf8");
  const drift = [
    ...listDrift("package.json#exports", modules, exportKeys, modules),
    ...listDrift(
      "src/index.ts",
      modules.filter((name) => EXCEPTIONS[name]?.omitFrom !== "barrel"),
      barrelModules(barrel),
      modules,
    ),
  ];
  if (drift.length > 0) return drift;
  // Same members, so what is left is order, targets or hand-edited lines.
  const exportsMatch =
    JSON.stringify(exports) === JSON.stringify(expectedExports(modules));
  return [
    ...(exportsMatch
      ? []
      : ["package.json#exports differs from what `pnpm roster:sync` writes"]),
    ...(barrel === expectedBarrel(modules)
      ? []
      : ["src/index.ts differs from what `pnpm roster:sync` writes"]),
  ];
}

async function writeFormatted(file: string, source: string): Promise<void> {
  const options = await resolveConfig(file);
  writeFileSync(file, await format(source, { ...options, filepath: file }));
}

/**
 * Derives `package.json#exports` and `src/index.ts` from the modules in
 * `src/`. Idempotent: a synced package is left byte-for-byte unchanged.
 */
export async function syncRoster(packageDir: string): Promise<void> {
  const modules = componentModules(packageDir);
  const manifest = readManifest(packageDir);
  manifest.exports = expectedExports(modules);
  await writeFormatted(
    join(packageDir, "package.json"),
    `${JSON.stringify(manifest, null, 2)}\n`,
  );
  await writeFormatted(barrelPath(packageDir), expectedBarrel(modules));
}
