import { describe, expect, test } from "vitest";

import { generateClientEntrySource } from "./client-entry-codegen.js";

describe("generateClientEntrySource", () => {
  test("emits one side-effect import per `theme.css` entry", () => {
    const source = generateClientEntrySource(["./src/global.css"]);
    // Root-relative slash form (`/src/global.css`) so Vite resolves
    // against the project root, not the generated entry's location
    // (`.plumix/client-entry.ts`).
    expect(source).toContain('import "/src/global.css";');
  });

  test("preserves entry order (matches the source array)", () => {
    const source = generateClientEntrySource([
      "./src/reset.css",
      "./src/tailwind.css",
      "./src/theme.css",
    ]);
    const resetIdx = source.indexOf("/src/reset.css");
    const tailwindIdx = source.indexOf("/src/tailwind.css");
    const themeIdx = source.indexOf("/src/theme.css");
    expect(resetIdx).toBeGreaterThan(0);
    expect(tailwindIdx).toBeGreaterThan(resetIdx);
    expect(themeIdx).toBeGreaterThan(tailwindIdx);
  });

  test("an empty array produces a valid ESM module with no imports", () => {
    const source = generateClientEntrySource([]);
    expect(source).not.toContain("import ");
    // Must still be a module (no statements at all would have Vite
    // treat the file as a script with implicit globals).
    expect(source).toContain("export {};");
  });

  test("quotes paths via JSON.stringify so backslashes / quotes are escaped", () => {
    const source = generateClientEntrySource(['./weird"name.css']);
    expect(source).toContain('import "/weird\\"name.css";');
  });

  test("passes through absolute paths and aliased specifiers verbatim", () => {
    // `~/...` and `@/...` are common alias prefixes; absolute paths are
    // already root-relative. None of these should get a leading slash
    // re-applied.
    const source = generateClientEntrySource([
      "~/assets/main.css",
      "@/styles/global.css",
      "/already/absolute.css",
    ]);
    expect(source).toContain('import "~/assets/main.css";');
    expect(source).toContain('import "@/styles/global.css";');
    expect(source).toContain('import "/already/absolute.css";');
  });

  test("always emits the do-not-edit header", () => {
    const source = generateClientEntrySource([]);
    expect(source).toContain("Generated by plumix");
    expect(source).toContain("do not edit");
  });
});
