/**
 * Synthesize the client entry that Vite bundles for the theme's
 * `css: []` array. This is the Nuxt pattern — the strings declared on
 * `ThemeDescriptor.css` never enter jiti's module graph (jiti can't
 * resolve CSS / image imports), but the generated file IS in Vite's
 * graph, so Vite resolves and hashes them like any other import.
 *
 * The generated module exports nothing — every import is a side
 * effect, exactly as if a hand-written client entry did
 * `import "./global.css"`.
 */
export function generateClientEntrySource(
  themeCss: readonly string[],
): string {
  const lines = [
    "// Generated by plumix — do not edit.",
    "// Re-emitted on each build from the theme's `css: []` array.",
    "",
  ];
  for (const path of themeCss) {
    lines.push(`import ${JSON.stringify(toClientEntryImport(path))};`);
  }
  if (themeCss.length === 0) {
    // Empty `export` keeps this file a module (TypeScript / Vite both
    // treat a bare file with zero statements as a script, which would
    // leak globals).
    lines.push("export {};");
  }
  return lines.join("\n") + "\n";
}

// Convert a theme-author path to one Vite resolves against the project
// root rather than against `.plumix/client-entry.ts`. Vite treats a
// leading `/` as project-root-relative; absolute paths and aliased
// specifiers (`~/...`, `@/...`, scoped npm packages like `@plumix/...`)
// already resolve correctly and pass through untouched. `../` also
// passes through — the rare case of pointing above the project root
// stays as a relative escape hatch from `.plumix/client-entry.ts`.
function toClientEntryImport(path: string): string {
  if (path.startsWith("/") || path.startsWith("~") || path.startsWith("@")) {
    return path;
  }
  if (path.startsWith("../")) return path;
  if (path.startsWith("./")) return "/" + path.slice(2);
  return "/" + path;
}
