/**
 * Synthesize the client entry that Vite bundles for the theme's
 * `css: []` array. This is the Nuxt pattern — the strings declared on
 * `ThemeDescriptor.css` never enter jiti's module graph (jiti can't
 * resolve CSS / image imports), but the generated file IS in Vite's
 * graph, so Vite resolves and hashes them like any other import.
 *
 * The generated module exports nothing — every import is a side
 * effect, exactly as if a hand-written client entry did
 * `import "./global.css"`.
 */
export function generateClientEntrySource(themeCss: readonly string[]): string {
  const lines = [
    "// Generated by plumix — do not edit.",
    "// Re-emitted on each build from the theme's `css: []` array.",
    "",
  ];
  for (const path of themeCss) {
    lines.push(`import ${JSON.stringify(toClientEntryImport(path))};`);
  }
  // Install the dev-only client error tools (island dialog, terminal
  // forwarder, compile/import overlay) from the one dev script injected on
  // every public page (`devThemeStylesTag`), through the single core-owned
  // install point (#1676).
  lines.push("", DEV_CLIENT_INSTALL);
  if (themeCss.length === 0) {
    // Empty `export` keeps this file a module (TypeScript / Vite both
    // treat a bare file with zero statements as a script, which would
    // leak globals — the dynamic `import()` below is an expression, not a
    // static import declaration, so it does not make the file a module).
    lines.push("", "export {};");
  }
  return lines.join("\n") + "\n";
}

// `import.meta.hot` is the dev gate: Vite replaces it with `undefined` in a
// production build, so this whole block — and the dynamic import it guards,
// which carries the client tools' React DOM weight — is dead-code-eliminated
// from the built client bundle. The install runs lazily through the single
// core-owned entry point (`@plumix/core/dev-client`, reached via the `plumix`
// package), which wires up the island dialog, terminal forwarder, and compile
// overlay. A `vite:error` Vite already broadcast (the page loaded onto a broken
// module) would race the import and be lost now that Vite's own overlay is
// disabled, so a synchronous listener buffers that error and hands it over to
// replay on install.
const DEV_CLIENT_INSTALL = [
  "if (import.meta.hot) {",
  "  const hot = import.meta.hot;",
  "  let pending = null;",
  "  const capture = (payload) => { pending = payload; };",
  '  hot.on("vite:error", capture);',
  '  import("plumix/core/dev-client").then((mod) => {',
  "    mod.installDevClient({ hot, initialCompileError: pending });",
  '    hot.off("vite:error", capture);',
  "  });",
  "}",
].join("\n");

// Convert a theme-author path to one Vite resolves against the project
// root rather than against `.plumix/client-entry.ts`. Vite treats a
// leading `/` as project-root-relative; absolute paths and aliased
// specifiers (`~/...`, `@/...`, scoped npm packages like `@plumix/...`)
// already resolve correctly and pass through untouched. `../` also
// passes through — the rare case of pointing above the project root
// stays as a relative escape hatch from `.plumix/client-entry.ts`.
function toClientEntryImport(path: string): string {
  if (path.startsWith("/") || path.startsWith("~") || path.startsWith("@")) {
    return path;
  }
  if (path.startsWith("../")) return path;
  if (path.startsWith("./")) return "/" + path.slice(2);
  return "/" + path;
}
