/**
 * Theme CSS strings never enter jiti's graph, which can't resolve CSS, but
 * this generated file is in Vite's graph, so Vite resolves and hashes them.
 */
export function generateClientEntrySource(themeCss: readonly string[]): string {
  const lines = [
    "// Generated by plumix — do not edit.",
    "// Re-emitted on each build from the theme's `css: []` array.",
    "",
  ];
  for (const path of themeCss) {
    lines.push(`import ${JSON.stringify(toClientEntryImport(path))};`);
  }
  // Install the dev-only client error tools (island dialog, terminal
  // forwarder, compile/import overlay) from the one dev script injected on
  // every public page (`devThemeStylesTag`), through the single core-owned
  // install point (#1676).
  lines.push("", DEV_CLIENT_INSTALL);
  if (themeCss.length === 0) {
    // Keeps the file a module: a dynamic `import()` alone does not, and a
    // script would leak globals.
    lines.push("", "export {};");
  }
  return lines.join("\n") + "\n";
}

// `import.meta.hot` is undefined in production, so this block tree-shakes out.
// With Vite's overlay disabled, a sync listener buffers an already-broadcast
// `vite:error` for replay.
const DEV_CLIENT_INSTALL = [
  "if (import.meta.hot) {",
  "  const hot = import.meta.hot;",
  "  let pending = null;",
  "  const capture = (payload) => { pending = payload; };",
  '  hot.on("vite:error", capture);',
  '  import("plumix/core/dev-client").then((mod) => {',
  "    mod.installDevClient({ hot, initialCompileError: pending });",
  '    hot.off("vite:error", capture);',
  "  });",
  "}",
].join("\n");

// Vite reads a leading `/` as project-root-relative; absolute, aliased and
// `../` paths pass through.
function toClientEntryImport(path: string): string {
  if (path.startsWith("/") || path.startsWith("~") || path.startsWith("@")) {
    return path;
  }
  if (path.startsWith("../")) return path;
  if (path.startsWith("./")) return "/" + path.slice(2);
  return "/" + path;
}
