import { describe, expect, test } from "vitest";

import { generateClientEntrySource } from "./client-entry-codegen.js";

describe("generateClientEntrySource", () => {
  test("emits one side-effect import per `theme.css` entry", () => {
    const source = generateClientEntrySource(["./src/global.css"]);
    // Root-relative slash form (`/src/global.css`) so Vite resolves
    // against the project root, not the generated entry's location
    // (`.plumix/client-entry.ts`).
    expect(source).toContain('import "/src/global.css";');
  });

  test("preserves entry order (matches the source array)", () => {
    const source = generateClientEntrySource([
      "./src/reset.css",
      "./src/tailwind.css",
      "./src/theme.css",
    ]);
    const resetIdx = source.indexOf("/src/reset.css");
    const tailwindIdx = source.indexOf("/src/tailwind.css");
    const themeIdx = source.indexOf("/src/theme.css");
    expect(resetIdx).toBeGreaterThan(0);
    expect(tailwindIdx).toBeGreaterThan(resetIdx);
    expect(themeIdx).toBeGreaterThan(tailwindIdx);
  });

  test("an empty array produces a valid ESM module with no CSS imports", () => {
    const source = generateClientEntrySource([]);
    // No side-effect CSS import declarations.
    expect(source).not.toContain('import "/');
    expect(source).not.toContain(".css");
    // Must still be a module (no static import/export at all would have Vite
    // treat the file as a script with implicit globals — the install block is
    // only a dynamic `import()` expression).
    expect(source).toContain("export {};");
  });

  test.each([[[]], [["./src/global.css"]]])(
    "always installs the dev-only client tools via the core entry behind the hot gate (css: %j)",
    (css) => {
      const source = generateClientEntrySource(css);
      // Gated on `import.meta.hot` so it tree-shakes out of a production build.
      expect(source).toContain("if (import.meta.hot)");
      // Installed from the single core-owned entry point (#1676), not from the
      // blocks dev-error subpath.
      expect(source).toContain('import("plumix/core/dev-client")');
      expect(source).toContain(
        "installDevClient({ hot, initialCompileError: pending })",
      );
      expect(source).not.toContain("plumix/blocks/dev-error");
      // A synchronous listener buffers a pre-install vite:error to replay it.
      expect(source).toContain('hot.on("vite:error", capture)');
    },
  );

  test("quotes paths via JSON.stringify so backslashes / quotes are escaped", () => {
    const source = generateClientEntrySource(['./weird"name.css']);
    expect(source).toContain('import "/weird\\"name.css";');
  });

  test("passes through absolute paths and aliased specifiers verbatim", () => {
    // `~/...` and `@/...` are common alias prefixes; absolute paths are
    // already root-relative. None of these should get a leading slash
    // re-applied.
    const source = generateClientEntrySource([
      "~/assets/main.css",
      "@/styles/global.css",
      "/already/absolute.css",
    ]);
    expect(source).toContain('import "~/assets/main.css";');
    expect(source).toContain('import "@/styles/global.css";');
    expect(source).toContain('import "/already/absolute.css";');
  });

  test("always emits the do-not-edit header", () => {
    const source = generateClientEntrySource([]);
    expect(source).toContain("Generated by plumix");
    expect(source).toContain("do not edit");
  });
});
