import { describe, expect, test } from "vitest";

import { generateEditorEntrySource } from "./editor-entry-codegen.js";

describe("generateEditorEntrySource", () => {
  test("no plugin blocks → a bare bootEditor() call", () => {
    const source = generateEditorEntrySource([]);
    expect(source).toContain(
      'import { bootEditor } from "plumix/editor-runtime";',
    );
    expect(source).toContain("bootEditor();");
    expect(source).not.toContain("import pb");
  });

  test("imports each module's default export and spreads them into bootEditor", () => {
    const source = generateEditorEntrySource([
      "@plumix/plugin-media/blocks",
      "@acme/widgets/blocks",
    ]);
    expect(source).toContain('import pb0 from "@plumix/plugin-media/blocks";');
    expect(source).toContain('import pb1 from "@acme/widgets/blocks";');
    expect(source).toContain("bootEditor([...(pb0 ?? []), ...(pb1 ?? [])]);");
  });

  test("dedups a module declared by more than one plugin", () => {
    const source = generateEditorEntrySource([
      "@plumix/plugin-media/blocks",
      "@plumix/plugin-media/blocks",
    ]);
    expect(source).toContain('import pb0 from "@plumix/plugin-media/blocks";');
    expect(source).not.toContain("pb1");
    expect(source).toContain("bootEditor([...(pb0 ?? [])]);");
  });

  test("quotes specifiers via JSON.stringify", () => {
    const source = generateEditorEntrySource(['weird"name/blocks']);
    expect(source).toContain('import pb0 from "weird\\"name/blocks";');
  });

  test("always emits the do-not-edit header", () => {
    const source = generateEditorEntrySource([]);
    expect(source).toContain("Generated by plumix");
    expect(source).toContain("do not edit");
  });
});
