import type { BlockModuleRef } from "./block-module-resolver.js";
import {
  blockImportStatement,
  blockSpecsArrayExpr,
} from "./block-module-resolver.js";

/**
 * Generates `.plumix/editor-entry.ts` — the `plumix-editor` client chunk whose
 * `bootEditor()` mounts the iframe canvas. `blocks` are the browser-safe block
 * modules a theme (via its `blocks` field) and its plugins (via `registerBlock`
 * calls) declare, recovered from config source with the exact export each was
 * imported from; they're imported here and handed to `bootEditor` so the canvas
 * registry holds core + theme + plugin blocks. Without them the canvas is
 * core-only and warns "Unregistered block name" on any custom block.
 */
export function generateEditorEntrySource(
  blocks: readonly BlockModuleRef[],
): string {
  const header = "// Generated by plumix — do not edit.\n";
  const boot = 'import { bootEditor } from "plumix/editor-runtime";\n';
  if (blocks.length === 0) {
    return `${header}${boot}bootEditor();\n`;
  }
  const imports = blocks
    .map((ref, i) => `${blockImportStatement(ref, `pb${i}`)}\n`)
    .join("");
  // Normalize each import to an array (single spec, array, or missing export)
  // so the spread can't hit a non-iterable and take the canvas down at boot.
  const spread = blocks
    .map((_, i) => `...${blockSpecsArrayExpr(`pb${i}`)}`)
    .join(", ");
  return `${header}${boot}${imports}bootEditor([${spread}]);\n`;
}
