import { describe, expect, test } from "vitest";

import { generateEditorEntrySource } from "./editor-entry-codegen.js";

const ref = (module: string, exportName = "default") => ({
  module,
  exportName,
});

describe("generateEditorEntrySource", () => {
  test("no blocks → a bare bootEditor() call", () => {
    const source = generateEditorEntrySource([]);
    expect(source).toContain(
      'import { bootEditor } from "plumix/editor-runtime";',
    );
    expect(source).toContain("bootEditor();");
    expect(source).not.toContain("import pb");
  });

  test("default-import a default export", () => {
    const source = generateEditorEntrySource([
      ref("@plumix/plugin-media/blocks"),
      ref("@acme/widgets/blocks"),
    ]);
    expect(source).toContain('import pb0 from "@plumix/plugin-media/blocks";');
    expect(source).toContain('import pb1 from "@acme/widgets/blocks";');
  });

  test("named-import a named export", () => {
    const source = generateEditorEntrySource([
      ref("/pkgs/media/dist/media-blocks.js", "mediaBlocks"),
    ]);
    expect(source).toContain(
      'import { mediaBlocks as pb0 } from "/pkgs/media/dist/media-blocks.js";',
    );
  });

  test("normalizes each import so a single spec or missing export can't crash the spread", () => {
    const source = generateEditorEntrySource([ref("./blocks.js")]);
    // A single `registerBlock` spec becomes `[pb0]`, an array passes through,
    // a missing export becomes `[]` — never a non-iterable in the spread.
    expect(source).toContain(
      "bootEditor([...(Array.isArray(pb0) ? pb0 : pb0 ? [pb0] : [])]);",
    );
  });

  test("quotes specifiers via JSON.stringify", () => {
    const source = generateEditorEntrySource([ref('weird"name/blocks')]);
    expect(source).toContain('import pb0 from "weird\\"name/blocks";');
  });

  test("always emits the do-not-edit header", () => {
    const source = generateEditorEntrySource([]);
    expect(source).toContain("Generated by plumix");
    expect(source).toContain("do not edit");
  });
});
