/**
 * Generates `.plumix/editor-entry.ts` — the `plumix-editor` client chunk whose
 * `bootEditor()` mounts the iframe canvas. Each plugin that contributes blocks
 * declares an `editorBlocksModule` (a browser-safe default-exported
 * `BlockSpec[]`); they're imported here and handed to `bootEditor` so the canvas
 * registry holds core + plugin blocks. Without this the canvas is core-only and
 * warns "Unregistered block name" on any plugin block.
 */
export function generateEditorEntrySource(
  blockModules: readonly string[],
): string {
  const header = "// Generated by plumix — do not edit.\n";
  const boot = 'import { bootEditor } from "plumix/editor-runtime";\n';
  const modules = [...new Set(blockModules)];
  if (modules.length === 0) {
    return `${header}${boot}bootEditor();\n`;
  }
  const imports = modules
    .map((mod, i) => `import pb${i} from ${JSON.stringify(mod)};\n`)
    .join("");
  const spread = modules.map((_, i) => `...pb${i}`).join(", ");
  return `${header}${boot}${imports}bootEditor([${spread}]);\n`;
}
