import { isAbsolute, relative, sep } from "node:path";

import type { BlockModuleRef } from "./block-module-resolver.js";
import {
  blockImportStatement,
  blockSpecsArrayExpr,
} from "./block-module-resolver.js";

/**
 * Imports resolved files relative to `entryDir`: Vite's dependency scan skips
 * an already-resolved absolute specifier, so a CommonJS dependency would then
 * fail in the browser.
 */
export function generateEditorEntrySource(
  entryDir: string,
  blocks: readonly BlockModuleRef[],
  shortcodes: readonly BlockModuleRef[] = [],
): string {
  const header = "// Generated by plumix — do not edit.\n";
  const boot = 'import { bootEditor } from "plumix/editor-runtime";\n';
  if (blocks.length === 0 && shortcodes.length === 0) {
    return `${header}${boot}bootEditor();\n`;
  }
  const fromEntry = (ref: BlockModuleRef): BlockModuleRef =>
    isAbsolute(ref.module)
      ? { ...ref, module: relativeSpecifier(entryDir, ref.module) }
      : ref;
  const imports = [
    ...blocks.map((ref, i) => blockImportStatement(fromEntry(ref), `pb${i}`)),
    ...shortcodes.map((ref, i) =>
      blockImportStatement(fromEntry(ref), `ps${i}`),
    ),
  ]
    .map((statement) => `${statement}\n`)
    .join("");
  // Normalize each import to an array (single spec, array, or missing export)
  // so the spread can't hit a non-iterable and take the canvas down at boot.
  const spread = (refs: readonly BlockModuleRef[], prefix: string): string =>
    refs.map((_, i) => `...${blockSpecsArrayExpr(`${prefix}${i}`)}`).join(", ");
  return (
    `${header}${boot}${imports}` +
    `bootEditor({ blocks: [${spread(blocks, "pb")}], ` +
    `shortcodes: [${spread(shortcodes, "ps")}] });\n`
  );
}

function relativeSpecifier(fromDir: string, file: string): string {
  const path = relative(fromDir, file).split(sep).join("/");
  return path.startsWith(".") ? path : `./${path}`;
}
