import { describe, expect, test } from "vitest";

import { generateEditorEntrySource } from "./editor-entry-codegen.js";

const ref = (module: string, exportName = "default") => ({
  module,
  exportName,
});

describe("generateEditorEntrySource", () => {
  test("no blocks → a bare bootEditor() call", () => {
    const source = generateEditorEntrySource([]);
    expect(source).toContain(
      'import { bootEditor } from "plumix/editor-runtime";',
    );
    expect(source).toContain("bootEditor();");
    expect(source).not.toContain("import pb");
  });

  test("default-import a default export", () => {
    const source = generateEditorEntrySource([
      ref("@plumix/plugin-media/blocks"),
      ref("@acme/widgets/blocks"),
    ]);
    expect(source).toContain('import pb0 from "@plumix/plugin-media/blocks";');
    expect(source).toContain('import pb1 from "@acme/widgets/blocks";');
  });

  test("named-import a named export", () => {
    const source = generateEditorEntrySource([
      ref("/pkgs/media/dist/media-blocks.js", "mediaBlocks"),
    ]);
    expect(source).toContain(
      'import { mediaBlocks as pb0 } from "/pkgs/media/dist/media-blocks.js";',
    );
  });

  test("normalizes each import so a single spec or missing export can't crash the spread", () => {
    const source = generateEditorEntrySource([ref("./blocks.js")]);
    // A single `registerBlock` spec becomes `[pb0]`, an array passes through,
    // a missing export becomes `[]` — never a non-iterable in the spread.
    expect(source).toContain(
      "bootEditor({ blocks: [...(Array.isArray(pb0) ? pb0 : pb0 ? [pb0] : [])], shortcodes: [] });",
    );
  });

  test("imports shortcode modules and hands them to bootEditor in order", () => {
    const source = generateEditorEntrySource(
      [],
      [ref("/app/plugin/shortcodes.ts", "shortcodes"), ref("/app/theme/sc.ts")],
    );
    expect(source).toContain(
      'import { shortcodes as ps0 } from "/app/plugin/shortcodes.ts";',
    );
    expect(source).toContain('import ps1 from "/app/theme/sc.ts";');
    // Plugin before theme: the canvas registry is last-write-wins.
    expect(source).toContain(
      "bootEditor({ blocks: [], shortcodes: [...(Array.isArray(ps0) ? ps0 : ps0 ? [ps0] : []), ...(Array.isArray(ps1) ? ps1 : ps1 ? [ps1] : [])] });",
    );
  });

  test("quotes specifiers via JSON.stringify", () => {
    const source = generateEditorEntrySource([ref('weird"name/blocks')]);
    expect(source).toContain('import pb0 from "weird\\"name/blocks";');
  });

  test("always emits the do-not-edit header", () => {
    const source = generateEditorEntrySource([]);
    expect(source).toContain("Generated by plumix");
    expect(source).toContain("do not edit");
  });
});
