/** One installed plugin's compiled catalog for one locale. */
export interface PluginCatalogFile {
  readonly path: string;
  /** Whether this is the plugin's `sourceLocale` catalog. */
  readonly source: boolean;
}

/**
 * Translations load lazily. The source-locale catalog is imported eagerly: a
 * plugin may import it itself, and a lazy import of an already-held module
 * splits nothing off.
 */
export function generatePluginCatalogsSource(
  files: ReadonlyMap<string, readonly PluginCatalogFile[]>,
): string {
  const lines = ["// Generated by plumix — do not edit."];
  if (files.size === 0) {
    lines.push("export default {};");
    return lines.join("\n") + "\n";
  }
  const entries: string[] = [];
  let staticCount = 0;
  for (const [locale, catalogs] of files) {
    const loaders = catalogs.map(({ path, source }) => {
      if (!source) return `() => import(${JSON.stringify(path)})`;
      const binding = `catalog${String(staticCount++)}`;
      lines.push(`import * as ${binding} from ${JSON.stringify(path)};`);
      return `() => Promise.resolve(${binding})`;
    });
    entries.push(`  ${JSON.stringify(locale)}: [${loaders.join(", ")}],`);
  }
  lines.push("export default {", ...entries, "};");
  return lines.join("\n") + "\n";
}
