/**
 * Synthesize the body of the `virtual:plumix/plugin-catalogs` module: locale →
 * one lazy import per plugin catalog, which the generated entry hands to
 * `buildApp` so SSR block renders resolve plugin strings on a Worker with no
 * fs. Lazy so a locale the request never asks for is never loaded.
 */
export function generatePluginCatalogsSource(
  files: ReadonlyMap<string, readonly string[]>,
): string {
  const lines = ["// Generated by plumix — do not edit."];
  if (files.size === 0) {
    lines.push("export default {};");
    return lines.join("\n") + "\n";
  }
  lines.push("export default {");
  for (const [locale, paths] of files) {
    const loaders = paths.map(
      (path) => `() => import(${JSON.stringify(path)})`,
    );
    lines.push(`  ${JSON.stringify(locale)}: [${loaders.join(", ")}],`);
  }
  lines.push("};");
  return lines.join("\n") + "\n";
}
