/** One installed plugin's compiled catalog for one locale. */
export interface PluginCatalogFile {
  readonly path: string;
  /** Whether this is the plugin's `sourceLocale` catalog. */
  readonly source: boolean;
}

/**
 * Synthesize the body of the `virtual:plumix/plugin-catalogs` module: locale →
 * one loader per plugin catalog, which the generated entry hands to
 * `buildApp` so SSR block renders resolve plugin strings on a Worker with no
 * fs. Translations load lazily, so a locale the request never asks for is
 * never loaded. A source-locale catalog is imported up front: a plugin may
 * import it itself to format strings with no request in hand (forms does),
 * and a lazy import of a module the graph already holds splits nothing off.
 */
export function generatePluginCatalogsSource(
  files: ReadonlyMap<string, readonly PluginCatalogFile[]>,
): string {
  const lines = ["// Generated by plumix — do not edit."];
  if (files.size === 0) {
    lines.push("export default {};");
    return lines.join("\n") + "\n";
  }
  const entries: string[] = [];
  let staticCount = 0;
  for (const [locale, catalogs] of files) {
    const loaders = catalogs.map(({ path, source }) => {
      if (!source) return `() => import(${JSON.stringify(path)})`;
      const binding = `catalog${String(staticCount++)}`;
      lines.push(`import * as ${binding} from ${JSON.stringify(path)};`);
      return `() => Promise.resolve(${binding})`;
    });
    entries.push(`  ${JSON.stringify(locale)}: [${loaders.join(", ")}],`);
  }
  lines.push("export default {", ...entries, "};");
  return lines.join("\n") + "\n";
}
