/**
 * Synthesize the body of the `virtual:plumix/worker-exports` module: one
 * `export *` per contributed specifier (see `RuntimeAdapter.workerExports`
 * for why config surfaces named worker exports this way).
 */
export function generateWorkerExportsSource(
  specifiers: readonly string[],
): string {
  const lines = ["// Generated by plumix — do not edit."];
  for (const specifier of specifiers) {
    lines.push(`export * from ${JSON.stringify(specifier)};`);
  }
  if (specifiers.length === 0) {
    // Keep the file a module (a bare file with zero statements is a script,
    // which would leak globals).
    lines.push("export {};");
  }
  return lines.join("\n") + "\n";
}
