/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as EditorRouteImport } from "./routes/_editor";
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated";
import { Route as AuthRouteImport } from "./routes/_auth";
import { Route as AuthenticatedIndexRouteImport } from "./routes/_authenticated/index";
import { Route as AuthenticatedProfileRouteImport } from "./routes/_authenticated/profile";
import { Route as AuthLoginRouteImport } from "./routes/_auth/login";
import { Route as AuthBootstrapRouteImport } from "./routes/_auth/bootstrap";
import { Route as AuthenticatedUsersIndexRouteImport } from "./routes/_authenticated/users/index";
import { Route as AuthenticatedSettingsIndexRouteImport } from "./routes/_authenticated/settings/index";
import { Route as AuthenticatedUsersNewRouteImport } from "./routes/_authenticated/users/new";
import { Route as AuthenticatedUsersIdRouteImport } from "./routes/_authenticated/users/$id";
import { Route as AuthenticatedSettingsPageRouteImport } from "./routes/_authenticated/settings/$page";
import { Route as AuthenticatedPagesSplatRouteImport } from "./routes/_authenticated/pages/$";
import { Route as AuthAcceptInviteTokenRouteImport } from "./routes/_auth/accept-invite/$token";
import { Route as AuthenticatedTaxonomiesNameIndexRouteImport } from "./routes/_authenticated/taxonomies/$name/index";
import { Route as AuthenticatedEntriesSlugIndexRouteImport } from "./routes/_authenticated/entries/$slug/index";
import { Route as EditorEntriesSlugNewRouteImport } from "./routes/_editor/entries/$slug/new";
import { Route as EditorEntriesSlugIdRouteImport } from "./routes/_editor/entries/$slug/$id";
import { Route as AuthenticatedTaxonomiesNameNewRouteImport } from "./routes/_authenticated/taxonomies/$name/new";
import { Route as AuthenticatedTaxonomiesNameIdRouteImport } from "./routes/_authenticated/taxonomies/$name/$id";

const EditorRoute = EditorRouteImport.update({
  id: "/_editor",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRoute,
} as any);
const AuthBootstrapRoute = AuthBootstrapRouteImport.update({
  id: "/bootstrap",
  path: "/bootstrap",
  getParentRoute: () => AuthRoute,
} as any);
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: "/users/",
  path: "/users/",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: "/settings/",
    path: "/settings/",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedUsersNewRoute = AuthenticatedUsersNewRouteImport.update({
  id: "/users/new",
  path: "/users/new",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedUsersIdRoute = AuthenticatedUsersIdRouteImport.update({
  id: "/users/$id",
  path: "/users/$id",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedSettingsPageRoute =
  AuthenticatedSettingsPageRouteImport.update({
    id: "/settings/$page",
    path: "/settings/$page",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedPagesSplatRoute = AuthenticatedPagesSplatRouteImport.update({
  id: "/pages/$",
  path: "/pages/$",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthAcceptInviteTokenRoute = AuthAcceptInviteTokenRouteImport.update({
  id: "/accept-invite/$token",
  path: "/accept-invite/$token",
  getParentRoute: () => AuthRoute,
} as any);
const AuthenticatedTaxonomiesNameIndexRoute =
  AuthenticatedTaxonomiesNameIndexRouteImport.update({
    id: "/taxonomies/$name/",
    path: "/taxonomies/$name/",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedEntriesSlugIndexRoute =
  AuthenticatedEntriesSlugIndexRouteImport.update({
    id: "/entries/$slug/",
    path: "/entries/$slug/",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const EditorEntriesSlugNewRoute = EditorEntriesSlugNewRouteImport.update({
  id: "/entries/$slug/new",
  path: "/entries/$slug/new",
  getParentRoute: () => EditorRoute,
} as any);
const EditorEntriesSlugIdRoute = EditorEntriesSlugIdRouteImport.update({
  id: "/entries/$slug/$id",
  path: "/entries/$slug/$id",
  getParentRoute: () => EditorRoute,
} as any);
const AuthenticatedTaxonomiesNameNewRoute =
  AuthenticatedTaxonomiesNameNewRouteImport.update({
    id: "/taxonomies/$name/new",
    path: "/taxonomies/$name/new",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedTaxonomiesNameIdRoute =
  AuthenticatedTaxonomiesNameIdRouteImport.update({
    id: "/taxonomies/$name/$id",
    path: "/taxonomies/$name/$id",
    getParentRoute: () => AuthenticatedRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof AuthenticatedIndexRoute;
  "/bootstrap": typeof AuthBootstrapRoute;
  "/login": typeof AuthLoginRoute;
  "/profile": typeof AuthenticatedProfileRoute;
  "/accept-invite/$token": typeof AuthAcceptInviteTokenRoute;
  "/pages/$": typeof AuthenticatedPagesSplatRoute;
  "/settings/$page": typeof AuthenticatedSettingsPageRoute;
  "/users/$id": typeof AuthenticatedUsersIdRoute;
  "/users/new": typeof AuthenticatedUsersNewRoute;
  "/settings/": typeof AuthenticatedSettingsIndexRoute;
  "/users/": typeof AuthenticatedUsersIndexRoute;
  "/taxonomies/$name/$id": typeof AuthenticatedTaxonomiesNameIdRoute;
  "/taxonomies/$name/new": typeof AuthenticatedTaxonomiesNameNewRoute;
  "/entries/$slug/$id": typeof EditorEntriesSlugIdRoute;
  "/entries/$slug/new": typeof EditorEntriesSlugNewRoute;
  "/entries/$slug/": typeof AuthenticatedEntriesSlugIndexRoute;
  "/taxonomies/$name/": typeof AuthenticatedTaxonomiesNameIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof AuthenticatedIndexRoute;
  "/bootstrap": typeof AuthBootstrapRoute;
  "/login": typeof AuthLoginRoute;
  "/profile": typeof AuthenticatedProfileRoute;
  "/accept-invite/$token": typeof AuthAcceptInviteTokenRoute;
  "/pages/$": typeof AuthenticatedPagesSplatRoute;
  "/settings/$page": typeof AuthenticatedSettingsPageRoute;
  "/users/$id": typeof AuthenticatedUsersIdRoute;
  "/users/new": typeof AuthenticatedUsersNewRoute;
  "/settings": typeof AuthenticatedSettingsIndexRoute;
  "/users": typeof AuthenticatedUsersIndexRoute;
  "/taxonomies/$name/$id": typeof AuthenticatedTaxonomiesNameIdRoute;
  "/taxonomies/$name/new": typeof AuthenticatedTaxonomiesNameNewRoute;
  "/entries/$slug/$id": typeof EditorEntriesSlugIdRoute;
  "/entries/$slug/new": typeof EditorEntriesSlugNewRoute;
  "/entries/$slug": typeof AuthenticatedEntriesSlugIndexRoute;
  "/taxonomies/$name": typeof AuthenticatedTaxonomiesNameIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_auth": typeof AuthRouteWithChildren;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/_editor": typeof EditorRouteWithChildren;
  "/_auth/bootstrap": typeof AuthBootstrapRoute;
  "/_auth/login": typeof AuthLoginRoute;
  "/_authenticated/profile": typeof AuthenticatedProfileRoute;
  "/_authenticated/": typeof AuthenticatedIndexRoute;
  "/_auth/accept-invite/$token": typeof AuthAcceptInviteTokenRoute;
  "/_authenticated/pages/$": typeof AuthenticatedPagesSplatRoute;
  "/_authenticated/settings/$page": typeof AuthenticatedSettingsPageRoute;
  "/_authenticated/users/$id": typeof AuthenticatedUsersIdRoute;
  "/_authenticated/users/new": typeof AuthenticatedUsersNewRoute;
  "/_authenticated/settings/": typeof AuthenticatedSettingsIndexRoute;
  "/_authenticated/users/": typeof AuthenticatedUsersIndexRoute;
  "/_authenticated/taxonomies/$name/$id": typeof AuthenticatedTaxonomiesNameIdRoute;
  "/_authenticated/taxonomies/$name/new": typeof AuthenticatedTaxonomiesNameNewRoute;
  "/_editor/entries/$slug/$id": typeof EditorEntriesSlugIdRoute;
  "/_editor/entries/$slug/new": typeof EditorEntriesSlugNewRoute;
  "/_authenticated/entries/$slug/": typeof AuthenticatedEntriesSlugIndexRoute;
  "/_authenticated/taxonomies/$name/": typeof AuthenticatedTaxonomiesNameIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/bootstrap"
    | "/login"
    | "/profile"
    | "/accept-invite/$token"
    | "/pages/$"
    | "/settings/$page"
    | "/users/$id"
    | "/users/new"
    | "/settings/"
    | "/users/"
    | "/taxonomies/$name/$id"
    | "/taxonomies/$name/new"
    | "/entries/$slug/$id"
    | "/entries/$slug/new"
    | "/entries/$slug/"
    | "/taxonomies/$name/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/bootstrap"
    | "/login"
    | "/profile"
    | "/accept-invite/$token"
    | "/pages/$"
    | "/settings/$page"
    | "/users/$id"
    | "/users/new"
    | "/settings"
    | "/users"
    | "/taxonomies/$name/$id"
    | "/taxonomies/$name/new"
    | "/entries/$slug/$id"
    | "/entries/$slug/new"
    | "/entries/$slug"
    | "/taxonomies/$name";
  id:
    | "__root__"
    | "/_auth"
    | "/_authenticated"
    | "/_editor"
    | "/_auth/bootstrap"
    | "/_auth/login"
    | "/_authenticated/profile"
    | "/_authenticated/"
    | "/_auth/accept-invite/$token"
    | "/_authenticated/pages/$"
    | "/_authenticated/settings/$page"
    | "/_authenticated/users/$id"
    | "/_authenticated/users/new"
    | "/_authenticated/settings/"
    | "/_authenticated/users/"
    | "/_authenticated/taxonomies/$name/$id"
    | "/_authenticated/taxonomies/$name/new"
    | "/_editor/entries/$slug/$id"
    | "/_editor/entries/$slug/new"
    | "/_authenticated/entries/$slug/"
    | "/_authenticated/taxonomies/$name/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  EditorRoute: typeof EditorRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_editor": {
      id: "/_editor";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof EditorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/": {
      id: "/_authenticated/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/profile": {
      id: "/_authenticated/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof AuthenticatedProfileRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_auth/login": {
      id: "/_auth/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/bootstrap": {
      id: "/_auth/bootstrap";
      path: "/bootstrap";
      fullPath: "/bootstrap";
      preLoaderRoute: typeof AuthBootstrapRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_authenticated/users/": {
      id: "/_authenticated/users/";
      path: "/users";
      fullPath: "/users/";
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/settings/": {
      id: "/_authenticated/settings/";
      path: "/settings";
      fullPath: "/settings/";
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/users/new": {
      id: "/_authenticated/users/new";
      path: "/users/new";
      fullPath: "/users/new";
      preLoaderRoute: typeof AuthenticatedUsersNewRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/users/$id": {
      id: "/_authenticated/users/$id";
      path: "/users/$id";
      fullPath: "/users/$id";
      preLoaderRoute: typeof AuthenticatedUsersIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/settings/$page": {
      id: "/_authenticated/settings/$page";
      path: "/settings/$page";
      fullPath: "/settings/$page";
      preLoaderRoute: typeof AuthenticatedSettingsPageRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/pages/$": {
      id: "/_authenticated/pages/$";
      path: "/pages/$";
      fullPath: "/pages/$";
      preLoaderRoute: typeof AuthenticatedPagesSplatRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_auth/accept-invite/$token": {
      id: "/_auth/accept-invite/$token";
      path: "/accept-invite/$token";
      fullPath: "/accept-invite/$token";
      preLoaderRoute: typeof AuthAcceptInviteTokenRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_authenticated/taxonomies/$name/": {
      id: "/_authenticated/taxonomies/$name/";
      path: "/taxonomies/$name";
      fullPath: "/taxonomies/$name/";
      preLoaderRoute: typeof AuthenticatedTaxonomiesNameIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/entries/$slug/": {
      id: "/_authenticated/entries/$slug/";
      path: "/entries/$slug";
      fullPath: "/entries/$slug/";
      preLoaderRoute: typeof AuthenticatedEntriesSlugIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_editor/entries/$slug/new": {
      id: "/_editor/entries/$slug/new";
      path: "/entries/$slug/new";
      fullPath: "/entries/$slug/new";
      preLoaderRoute: typeof EditorEntriesSlugNewRouteImport;
      parentRoute: typeof EditorRoute;
    };
    "/_editor/entries/$slug/$id": {
      id: "/_editor/entries/$slug/$id";
      path: "/entries/$slug/$id";
      fullPath: "/entries/$slug/$id";
      preLoaderRoute: typeof EditorEntriesSlugIdRouteImport;
      parentRoute: typeof EditorRoute;
    };
    "/_authenticated/taxonomies/$name/new": {
      id: "/_authenticated/taxonomies/$name/new";
      path: "/taxonomies/$name/new";
      fullPath: "/taxonomies/$name/new";
      preLoaderRoute: typeof AuthenticatedTaxonomiesNameNewRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/taxonomies/$name/$id": {
      id: "/_authenticated/taxonomies/$name/$id";
      path: "/taxonomies/$name/$id";
      fullPath: "/taxonomies/$name/$id";
      preLoaderRoute: typeof AuthenticatedTaxonomiesNameIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
  }
}

interface AuthRouteChildren {
  AuthBootstrapRoute: typeof AuthBootstrapRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthAcceptInviteTokenRoute: typeof AuthAcceptInviteTokenRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthBootstrapRoute: AuthBootstrapRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthAcceptInviteTokenRoute: AuthAcceptInviteTokenRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute;
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute;
  AuthenticatedPagesSplatRoute: typeof AuthenticatedPagesSplatRoute;
  AuthenticatedSettingsPageRoute: typeof AuthenticatedSettingsPageRoute;
  AuthenticatedUsersIdRoute: typeof AuthenticatedUsersIdRoute;
  AuthenticatedUsersNewRoute: typeof AuthenticatedUsersNewRoute;
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute;
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute;
  AuthenticatedTaxonomiesNameIdRoute: typeof AuthenticatedTaxonomiesNameIdRoute;
  AuthenticatedTaxonomiesNameNewRoute: typeof AuthenticatedTaxonomiesNameNewRoute;
  AuthenticatedEntriesSlugIndexRoute: typeof AuthenticatedEntriesSlugIndexRoute;
  AuthenticatedTaxonomiesNameIndexRoute: typeof AuthenticatedTaxonomiesNameIndexRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPagesSplatRoute: AuthenticatedPagesSplatRoute,
  AuthenticatedSettingsPageRoute: AuthenticatedSettingsPageRoute,
  AuthenticatedUsersIdRoute: AuthenticatedUsersIdRoute,
  AuthenticatedUsersNewRoute: AuthenticatedUsersNewRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedTaxonomiesNameIdRoute: AuthenticatedTaxonomiesNameIdRoute,
  AuthenticatedTaxonomiesNameNewRoute: AuthenticatedTaxonomiesNameNewRoute,
  AuthenticatedEntriesSlugIndexRoute: AuthenticatedEntriesSlugIndexRoute,
  AuthenticatedTaxonomiesNameIndexRoute: AuthenticatedTaxonomiesNameIndexRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

interface EditorRouteChildren {
  EditorEntriesSlugIdRoute: typeof EditorEntriesSlugIdRoute;
  EditorEntriesSlugNewRoute: typeof EditorEntriesSlugNewRoute;
}

const EditorRouteChildren: EditorRouteChildren = {
  EditorEntriesSlugIdRoute: EditorEntriesSlugIdRoute,
  EditorEntriesSlugNewRoute: EditorEntriesSlugNewRoute,
};

const EditorRouteWithChildren =
  EditorRoute._addFileChildren(EditorRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  EditorRoute: EditorRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
