/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated";
import { Route as AuthRouteImport } from "./routes/_auth";
import { Route as AuthenticatedIndexRouteImport } from "./routes/_authenticated/index";
import { Route as AuthenticatedProfileRouteImport } from "./routes/_authenticated/profile";
import { Route as AuthLoginRouteImport } from "./routes/_auth/login";
import { Route as AuthBootstrapRouteImport } from "./routes/_auth/bootstrap";
import { Route as AuthenticatedUsersIndexRouteImport } from "./routes/_authenticated/users/index";
import { Route as AuthenticatedUsersNewRouteImport } from "./routes/_authenticated/users/new";
import { Route as AuthenticatedUsersIdRouteImport } from "./routes/_authenticated/users/$id";
import { Route as AuthAcceptInviteTokenRouteImport } from "./routes/_auth/accept-invite/$token";
import { Route as AuthenticatedTaxonomiesNameIndexRouteImport } from "./routes/_authenticated/taxonomies/$name/index";
import { Route as AuthenticatedContentSlugIndexRouteImport } from "./routes/_authenticated/content/$slug/index";
import { Route as AuthenticatedTaxonomiesNameNewRouteImport } from "./routes/_authenticated/taxonomies/$name/new";
import { Route as AuthenticatedTaxonomiesNameIdRouteImport } from "./routes/_authenticated/taxonomies/$name/$id";
import { Route as AuthenticatedContentSlugNewRouteImport } from "./routes/_authenticated/content/$slug/new";
import { Route as AuthenticatedContentSlugIdRouteImport } from "./routes/_authenticated/content/$slug/$id";

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRoute,
} as any);
const AuthBootstrapRoute = AuthBootstrapRouteImport.update({
  id: "/bootstrap",
  path: "/bootstrap",
  getParentRoute: () => AuthRoute,
} as any);
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: "/users/",
  path: "/users/",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedUsersNewRoute = AuthenticatedUsersNewRouteImport.update({
  id: "/users/new",
  path: "/users/new",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedUsersIdRoute = AuthenticatedUsersIdRouteImport.update({
  id: "/users/$id",
  path: "/users/$id",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthAcceptInviteTokenRoute = AuthAcceptInviteTokenRouteImport.update({
  id: "/accept-invite/$token",
  path: "/accept-invite/$token",
  getParentRoute: () => AuthRoute,
} as any);
const AuthenticatedTaxonomiesNameIndexRoute =
  AuthenticatedTaxonomiesNameIndexRouteImport.update({
    id: "/taxonomies/$name/",
    path: "/taxonomies/$name/",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedContentSlugIndexRoute =
  AuthenticatedContentSlugIndexRouteImport.update({
    id: "/content/$slug/",
    path: "/content/$slug/",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedTaxonomiesNameNewRoute =
  AuthenticatedTaxonomiesNameNewRouteImport.update({
    id: "/taxonomies/$name/new",
    path: "/taxonomies/$name/new",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedTaxonomiesNameIdRoute =
  AuthenticatedTaxonomiesNameIdRouteImport.update({
    id: "/taxonomies/$name/$id",
    path: "/taxonomies/$name/$id",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedContentSlugNewRoute =
  AuthenticatedContentSlugNewRouteImport.update({
    id: "/content/$slug/new",
    path: "/content/$slug/new",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedContentSlugIdRoute =
  AuthenticatedContentSlugIdRouteImport.update({
    id: "/content/$slug/$id",
    path: "/content/$slug/$id",
    getParentRoute: () => AuthenticatedRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof AuthenticatedIndexRoute;
  "/bootstrap": typeof AuthBootstrapRoute;
  "/login": typeof AuthLoginRoute;
  "/profile": typeof AuthenticatedProfileRoute;
  "/accept-invite/$token": typeof AuthAcceptInviteTokenRoute;
  "/users/$id": typeof AuthenticatedUsersIdRoute;
  "/users/new": typeof AuthenticatedUsersNewRoute;
  "/users/": typeof AuthenticatedUsersIndexRoute;
  "/content/$slug/$id": typeof AuthenticatedContentSlugIdRoute;
  "/content/$slug/new": typeof AuthenticatedContentSlugNewRoute;
  "/taxonomies/$name/$id": typeof AuthenticatedTaxonomiesNameIdRoute;
  "/taxonomies/$name/new": typeof AuthenticatedTaxonomiesNameNewRoute;
  "/content/$slug/": typeof AuthenticatedContentSlugIndexRoute;
  "/taxonomies/$name/": typeof AuthenticatedTaxonomiesNameIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof AuthenticatedIndexRoute;
  "/bootstrap": typeof AuthBootstrapRoute;
  "/login": typeof AuthLoginRoute;
  "/profile": typeof AuthenticatedProfileRoute;
  "/accept-invite/$token": typeof AuthAcceptInviteTokenRoute;
  "/users/$id": typeof AuthenticatedUsersIdRoute;
  "/users/new": typeof AuthenticatedUsersNewRoute;
  "/users": typeof AuthenticatedUsersIndexRoute;
  "/content/$slug/$id": typeof AuthenticatedContentSlugIdRoute;
  "/content/$slug/new": typeof AuthenticatedContentSlugNewRoute;
  "/taxonomies/$name/$id": typeof AuthenticatedTaxonomiesNameIdRoute;
  "/taxonomies/$name/new": typeof AuthenticatedTaxonomiesNameNewRoute;
  "/content/$slug": typeof AuthenticatedContentSlugIndexRoute;
  "/taxonomies/$name": typeof AuthenticatedTaxonomiesNameIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_auth": typeof AuthRouteWithChildren;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/_auth/bootstrap": typeof AuthBootstrapRoute;
  "/_auth/login": typeof AuthLoginRoute;
  "/_authenticated/profile": typeof AuthenticatedProfileRoute;
  "/_authenticated/": typeof AuthenticatedIndexRoute;
  "/_auth/accept-invite/$token": typeof AuthAcceptInviteTokenRoute;
  "/_authenticated/users/$id": typeof AuthenticatedUsersIdRoute;
  "/_authenticated/users/new": typeof AuthenticatedUsersNewRoute;
  "/_authenticated/users/": typeof AuthenticatedUsersIndexRoute;
  "/_authenticated/content/$slug/$id": typeof AuthenticatedContentSlugIdRoute;
  "/_authenticated/content/$slug/new": typeof AuthenticatedContentSlugNewRoute;
  "/_authenticated/taxonomies/$name/$id": typeof AuthenticatedTaxonomiesNameIdRoute;
  "/_authenticated/taxonomies/$name/new": typeof AuthenticatedTaxonomiesNameNewRoute;
  "/_authenticated/content/$slug/": typeof AuthenticatedContentSlugIndexRoute;
  "/_authenticated/taxonomies/$name/": typeof AuthenticatedTaxonomiesNameIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/bootstrap"
    | "/login"
    | "/profile"
    | "/accept-invite/$token"
    | "/users/$id"
    | "/users/new"
    | "/users/"
    | "/content/$slug/$id"
    | "/content/$slug/new"
    | "/taxonomies/$name/$id"
    | "/taxonomies/$name/new"
    | "/content/$slug/"
    | "/taxonomies/$name/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/bootstrap"
    | "/login"
    | "/profile"
    | "/accept-invite/$token"
    | "/users/$id"
    | "/users/new"
    | "/users"
    | "/content/$slug/$id"
    | "/content/$slug/new"
    | "/taxonomies/$name/$id"
    | "/taxonomies/$name/new"
    | "/content/$slug"
    | "/taxonomies/$name";
  id:
    | "__root__"
    | "/_auth"
    | "/_authenticated"
    | "/_auth/bootstrap"
    | "/_auth/login"
    | "/_authenticated/profile"
    | "/_authenticated/"
    | "/_auth/accept-invite/$token"
    | "/_authenticated/users/$id"
    | "/_authenticated/users/new"
    | "/_authenticated/users/"
    | "/_authenticated/content/$slug/$id"
    | "/_authenticated/content/$slug/new"
    | "/_authenticated/taxonomies/$name/$id"
    | "/_authenticated/taxonomies/$name/new"
    | "/_authenticated/content/$slug/"
    | "/_authenticated/taxonomies/$name/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/": {
      id: "/_authenticated/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/profile": {
      id: "/_authenticated/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof AuthenticatedProfileRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_auth/login": {
      id: "/_auth/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/bootstrap": {
      id: "/_auth/bootstrap";
      path: "/bootstrap";
      fullPath: "/bootstrap";
      preLoaderRoute: typeof AuthBootstrapRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_authenticated/users/": {
      id: "/_authenticated/users/";
      path: "/users";
      fullPath: "/users/";
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/users/new": {
      id: "/_authenticated/users/new";
      path: "/users/new";
      fullPath: "/users/new";
      preLoaderRoute: typeof AuthenticatedUsersNewRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/users/$id": {
      id: "/_authenticated/users/$id";
      path: "/users/$id";
      fullPath: "/users/$id";
      preLoaderRoute: typeof AuthenticatedUsersIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_auth/accept-invite/$token": {
      id: "/_auth/accept-invite/$token";
      path: "/accept-invite/$token";
      fullPath: "/accept-invite/$token";
      preLoaderRoute: typeof AuthAcceptInviteTokenRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_authenticated/taxonomies/$name/": {
      id: "/_authenticated/taxonomies/$name/";
      path: "/taxonomies/$name";
      fullPath: "/taxonomies/$name/";
      preLoaderRoute: typeof AuthenticatedTaxonomiesNameIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/content/$slug/": {
      id: "/_authenticated/content/$slug/";
      path: "/content/$slug";
      fullPath: "/content/$slug/";
      preLoaderRoute: typeof AuthenticatedContentSlugIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/taxonomies/$name/new": {
      id: "/_authenticated/taxonomies/$name/new";
      path: "/taxonomies/$name/new";
      fullPath: "/taxonomies/$name/new";
      preLoaderRoute: typeof AuthenticatedTaxonomiesNameNewRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/taxonomies/$name/$id": {
      id: "/_authenticated/taxonomies/$name/$id";
      path: "/taxonomies/$name/$id";
      fullPath: "/taxonomies/$name/$id";
      preLoaderRoute: typeof AuthenticatedTaxonomiesNameIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/content/$slug/new": {
      id: "/_authenticated/content/$slug/new";
      path: "/content/$slug/new";
      fullPath: "/content/$slug/new";
      preLoaderRoute: typeof AuthenticatedContentSlugNewRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/content/$slug/$id": {
      id: "/_authenticated/content/$slug/$id";
      path: "/content/$slug/$id";
      fullPath: "/content/$slug/$id";
      preLoaderRoute: typeof AuthenticatedContentSlugIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
  }
}

interface AuthRouteChildren {
  AuthBootstrapRoute: typeof AuthBootstrapRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthAcceptInviteTokenRoute: typeof AuthAcceptInviteTokenRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthBootstrapRoute: AuthBootstrapRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthAcceptInviteTokenRoute: AuthAcceptInviteTokenRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute;
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute;
  AuthenticatedUsersIdRoute: typeof AuthenticatedUsersIdRoute;
  AuthenticatedUsersNewRoute: typeof AuthenticatedUsersNewRoute;
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute;
  AuthenticatedContentSlugIdRoute: typeof AuthenticatedContentSlugIdRoute;
  AuthenticatedContentSlugNewRoute: typeof AuthenticatedContentSlugNewRoute;
  AuthenticatedTaxonomiesNameIdRoute: typeof AuthenticatedTaxonomiesNameIdRoute;
  AuthenticatedTaxonomiesNameNewRoute: typeof AuthenticatedTaxonomiesNameNewRoute;
  AuthenticatedContentSlugIndexRoute: typeof AuthenticatedContentSlugIndexRoute;
  AuthenticatedTaxonomiesNameIndexRoute: typeof AuthenticatedTaxonomiesNameIndexRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedUsersIdRoute: AuthenticatedUsersIdRoute,
  AuthenticatedUsersNewRoute: AuthenticatedUsersNewRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedContentSlugIdRoute: AuthenticatedContentSlugIdRoute,
  AuthenticatedContentSlugNewRoute: AuthenticatedContentSlugNewRoute,
  AuthenticatedTaxonomiesNameIdRoute: AuthenticatedTaxonomiesNameIdRoute,
  AuthenticatedTaxonomiesNameNewRoute: AuthenticatedTaxonomiesNameNewRoute,
  AuthenticatedContentSlugIndexRoute: AuthenticatedContentSlugIndexRoute,
  AuthenticatedTaxonomiesNameIndexRoute: AuthenticatedTaxonomiesNameIndexRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
