import type { EntrySourceOptions } from "plumix";

/**
 * The Bun entry: imports and calls only; the process is `serveProcess`.
 *
 * Its default export is conditional because Bun serves any default export
 * carrying a `fetch` property itself, beside whatever the module started, so
 * a site exporting its handler would bind the port twice. Run directly, the
 * entry exports the `Server`, which Bun does not serve again; imported to be
 * embedded, it exports the portable `{ fetch, scheduled }` and starts
 * nothing.
 */
export function generateEntry({ configModule }: EntrySourceOptions): string {
  const lines = [
    "// Generated by plumix — do not edit.",
    "// Regenerated from plumix.config.ts on each build.",
    "",
    'import { createBunSite, loadEnvFileWhenMain, serveProcess } from "@plumix/runtime-bun";',
    // The plumix Vite plugin resolves this: `{}` in dev, the client's
    // `.vite/manifest.json` in a build, so SSR can inject the hashed
    // stylesheet links.
    'import assetManifest from "virtual:plumix/asset-manifest";',
    // Each plugin's compiled catalogs by locale, for SSR block render strings.
    'import pluginCatalogs from "virtual:plumix/plugin-catalogs";',
    `import config from ${JSON.stringify(configModule)};`,
    "",
    'export * from "virtual:plumix/worker-exports";',
    "",
    // Before the site is built, so the env it snapshots carries the file.
    "loadEnvFileWhenMain(import.meta.main);",
    "const site = createBunSite({",
    "  config,",
    "  assetManifest,",
    "  pluginCatalogs,",
    "  entryUrl: import.meta.url,",
    "});",
    "",
    "export const dispose = site.dispose;",
    "export default import.meta.main ? serveProcess(site) : site.handler;",
    "",
  ];
  return lines.join("\n");
}
