import type { EntrySourceOptions } from "plumix";

/**
 * Bun serves any default export with a `fetch` itself, so a run-directly entry
 * exports the `Server` instead, and an embedded one exports `{ fetch, scheduled
 * }`.
 */
export function generateEntry({ configModule }: EntrySourceOptions): string {
  const lines = [
    "// Generated by plumix — do not edit.",
    "// Regenerated from plumix.config.ts on each build.",
    "",
    'import { createBunSite, loadEnvFileWhenMain, serveProcess } from "@plumix/runtime-bun";',
    // The plumix Vite plugin resolves this: `{}` in dev, the client's
    // `.vite/manifest.json` in a build, so SSR can inject the hashed
    // stylesheet links.
    'import assetManifest from "virtual:plumix/asset-manifest";',
    // Each plugin's compiled catalogs by locale, for SSR block render strings.
    'import pluginCatalogs from "virtual:plumix/plugin-catalogs";',
    `import config from ${JSON.stringify(configModule)};`,
    "",
    'export * from "virtual:plumix/worker-exports";',
    "",
    // Before the site is built, so the env it snapshots carries the file.
    "loadEnvFileWhenMain(import.meta.main);",
    "const site = createBunSite({",
    "  config,",
    "  assetManifest,",
    "  pluginCatalogs,",
    "  entryUrl: import.meta.url,",
    "});",
    "",
    "export const dispose = site.dispose;",
    "export default import.meta.main ? serveProcess(site) : site.handler;",
    "",
  ];
  return lines.join("\n");
}
