// What a theme file writes: the descriptor, its templates, the rules that
// place them in the hierarchy, and the data each template receives. The
// render components (`<Link>`, `<Image>`, `BlockRenderer`) are on
// `plumix/blocks/renderer`; `ThemeDescriptor` is on the root, the one module a
// theme's `declare module "plumix"` augmentation reaches.
export {
  archive,
  author,
  date,
  defineTemplate,
  defineTheme,
  entry,
  fallback,
  forArchiveType,
  forAuthor,
  forDate,
  forEntryType,
  forTermTaxonomy,
  frontPage,
  isArchive,
  isAuthor,
  isCustom,
  isDate,
  isEntry,
  isError,
  isFrontPage,
  isSearch,
  isTaxonomy,
  notFound,
  search,
  serverError,
  taxonomy,
  ThemeError,
  ThemeRegistrationError,
} from "@plumix/core";

export type {
  ArchiveData,
  ArchiveDataOf,
  ArchiveTypeName,
  AuthorArchiveData,
  CustomArchiveData,
  DateArchiveData,
  DocumentLink,
  DocumentManifest,
  DocumentMeta,
  DocumentScript,
  EntryData,
  EntryProjection,
  EntryTypeName,
  ErrorData,
  FrontPageData,
  Pagination,
  ResolvedAuthor,
  ResolvedEntry,
  ResolvedEntryFor,
  ResolvedTerm,
  ResolvedTermFor,
  SearchData,
  TaxonomyData,
  Template,
  TemplateComponent,
  TemplateData,
  TemplateDepKey,
  TemplateDepLoader,
  TemplateEntry,
  TemplateRender,
  TemplateRenderArgs,
  TemplateRule,
  TermProjection,
  TermTaxonomyName,
} from "@plumix/core";
