// `ThemeDescriptor` lives on the root, the one module a theme's `declare module
// "plumix"` reaches.
export {
  author,
  date,
  defineTemplate,
  defineTheme,
  entry,
  entryType,
  fallback,
  forArchiveType,
  forAuthor,
  forDate,
  forEntryType,
  forTermTaxonomy,
  forView,
  frontPage,
  isArchiveType,
  isAuthor,
  isDate,
  isEntry,
  isEntryType,
  isError,
  isFrontPage,
  isSearch,
  isTerm,
  isView,
  notFound,
  search,
  serverError,
  term,
  ThemeError,
  ThemeRegistrationError,
  transitionName,
  viewTransitionTypes,
} from "@plumix/core";

export type {
  ArchiveDataOf,
  ArchiveTypeData,
  ArchiveTypeName,
  AuthorArchiveData,
  DateArchiveData,
  DocumentLink,
  DocumentManifest,
  DocumentMeta,
  DocumentScript,
  EntryData,
  EntryProjection,
  EntryTypeArchiveData,
  EntryTypeName,
  ErrorData,
  FrontPageData,
  ListingArchiveData,
  Pagination,
  ResolvedAuthor,
  ResolvedEntry,
  ResolvedEntryFor,
  ResolvedTerm,
  ResolvedTermFor,
  SearchData,
  TermArchiveData,
  Template,
  TemplateComponent,
  TemplateData,
  TemplateDepKey,
  TemplateDepLoader,
  TemplateEntry,
  TemplateRender,
  TemplateRenderArgs,
  TemplateRule,
  TermProjection,
  TermTaxonomyName,
  ViewData,
  ViewDataOf,
  ViewTransitionsInput,
  ViewTransitionType,
} from "@plumix/core";
