// Every icon is named explicitly, never `export *`: a namespace re-export plus
// <BlockIcon>'s runtime lookup pulls all of lucide (~600 KB) into the editor
// chunk.
import type { LucideIcon } from "lucide-react";
// Bindings for the blockIcons map (block-declared icons, resolved by string).
import {
  AlignLeft,
  Box,
  ChevronDown,
  Code,
  Columns,
  File,
  Group,
  Image,
  Images,
  LayoutTemplate,
  List,
  ListOrdered,
  Megaphone,
  Minus,
  MousePointerClick,
  Music,
  Rows,
  Square,
  Table,
  Type,
  Video,
} from "lucide-react";

export type { LucideIcon };

// Statically-referenced icons (admin + admin-editor components).
export {
  AlertTriangle,
  AlignCenter,
  AlignLeft,
  AlignRight,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Bold,
  Calendar,
  Check,
  ChevronDownIcon,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Circle,
  ClipboardPaste,
  Code2,
  Copy,
  CopyPlus,
  CornerLeftUp,
  Eye,
  EyeIcon,
  EyeOff,
  FileText,
  Folder,
  Globe,
  GripVertical,
  Group,
  Highlighter,
  History,
  Image,
  Italic,
  Key,
  Keyboard,
  Layout,
  LayoutDashboard,
  LayoutTemplate,
  Link2,
  Link2Icon,
  List,
  ListOrdered,
  LogOut,
  Mail,
  MessageCircle,
  MessageCircleMore,
  Minus,
  Monitor,
  MoreHorizontal,
  MoreVertical,
  PanelLeft,
  Pencil,
  Play,
  Plus,
  PlusIcon,
  Puzzle,
  Quote,
  Redo2,
  RefreshCw,
  RemoveFormatting,
  Search,
  Settings,
  SettingsIcon,
  Smartphone,
  Square,
  SquareDashed,
  Strikethrough,
  Subscript,
  Superscript,
  Tablet,
  Tag,
  Trash2,
  TriangleAlert,
  Tv,
  Underline,
  Undo2,
  Ungroup,
  User,
  UserPlus,
  Users,
  Watch,
  X,
  ZoomIn,
  ZoomOut,
} from "lucide-react";

// Block-declared icons. <BlockIcon> looks names up here at render time. Add an
// entry when a block ships a new `icon: "..."`.
export const blockIcons = {
  AlignLeft,
  Box,
  ChevronDown,
  Code,
  Columns,
  File,
  Group,
  Image,
  Images,
  LayoutTemplate,
  List,
  ListOrdered,
  Megaphone,
  Minus,
  MousePointerClick,
  Music,
  Rows,
  Table,
  Type,
  Video,
} satisfies Record<string, LucideIcon>;

export const fallbackBlockIcon = Square;
