import type { EntrySourceOptions } from "plumix";

/**
 * The Node entry: imports and calls only. Everything it used to spell out —
 * the shutdown protocol, the cron start, the serve chain — is
 * `createNodeSite`; see the rule stated there (#2303).
 */
export function generateEntry({ configModule }: EntrySourceOptions): string {
  const lines = [
    "// Generated by plumix — do not edit.",
    "// Regenerated from plumix.config.ts on each build.",
    "",
    'import { createNodeSite } from "@plumix/runtime-node";',
    // The plumix Vite plugin resolves this: `{}` in dev, the client's
    // `.vite/manifest.json` in a build, so SSR can inject the hashed
    // stylesheet links.
    'import assetManifest from "virtual:plumix/asset-manifest";',
    `import config from ${JSON.stringify(configModule)};`,
    "",
    'export * from "virtual:plumix/worker-exports";',
    "",
    "const site = createNodeSite({",
    "  config,",
    "  assetManifest,",
    "  entryUrl: import.meta.url,",
    "});",
    "",
    // The portable `{ fetch, scheduled }` pair, as a Worker exports it.
    "export default site.handler;",
    "export const listener = site.listener;",
    "export const startCron = site.startCron;",
    "",
    // Only when run directly: an `http` server in front of the serve chain.
    // Imported to be embedded, this starts nothing.
    "site.serveWhenMain(import.meta.main);",
    "",
  ];
  return lines.join("\n");
}
