import type { EntrySourceOptions } from "plumix";

import { ASSETS_DIR_ENV, DRAIN_DEADLINE_MS } from "./entry-constants.js";

/**
 * The Node entry: the portable `{ fetch, scheduled }` default export, a
 * Connect-style `listener` for embedding — the assets and image layers ahead
 * of the bridge — and, only when run directly, an `http` server in front of it.
 */
export function generateEntry({ configModule }: EntrySourceOptions): string {
  const lines = [
    "// Generated by plumix — do not edit.",
    "// Regenerated from plumix.config.ts on each build.",
    "",
    'import { createServer } from "node:http";',
    'import { dirname, resolve } from "node:path";',
    'import { setTimeout as sleep } from "node:timers/promises";',
    'import { fileURLToPath } from "node:url";',
    'import { buildApp, renderDevBootErrorResponse } from "plumix";',
    'import { createAssetsLayer, createImageLayer, createRequestListener, startScheduledRunner } from "@plumix/runtime-node";',
    // The plumix Vite plugin resolves this: `{}` in dev, the client's
    // `.vite/manifest.json` in a build, so SSR can inject the hashed
    // stylesheet links.
    'import assetManifest from "virtual:plumix/asset-manifest";',
    `import config from ${JSON.stringify(configModule)};`,
    "",
    'export * from "virtual:plumix/worker-exports";',
    "",
    // Read once, at start. The assets directory is named on it so the handler
    // serves `dist/client` beside this module, the way Cloudflare's handler
    // reads `env.ASSETS`.
    "const env = {",
    "  ...process.env,",
    `  ${ASSETS_DIR_ENV}: resolve(dirname(fileURLToPath(import.meta.url)), "../client"),`,
    "};",
    "",
    "const appPromise = buildApp(config, {",
    "  assetManifest,",
    "});",
    "let handler;",
    "",
    "const site = {",
    "  async fetch(request, invocation = { env }) {",
    "    let app;",
    "    try {",
    "      app = await appPromise;",
    "    } catch (bootError) {",
    // Dev-only, statically false in a build so the branch and the renderer
    // tree-shake out; see the Cloudflare entry.
    "      if (process.env.PLUMIX_DEV) {",
    "        return renderDevBootErrorResponse(bootError);",
    "      }",
    "      throw bootError;",
    "    }",
    "    handler ??= config.runtime.createHandler(app);",
    "    return handler.fetch(request, invocation);",
    "  },",
    "  async scheduled(event, invocation = { env }) {",
    "    const app = await appPromise;",
    "    handler ??= config.runtime.createHandler(app);",
    "    if (handler.scheduled) await handler.scheduled(event, invocation);",
    "  },",
    "};",
    "",
    "export default site;",
    "",
    "const { trustProxy, bodySizeLimit } = config.runtime.config;",
    `const assets = createAssetsLayer({ root: env.${ASSETS_DIR_ENV} });`,
    "const bridge = createRequestListener(",
    "  (request, meta) => site.fetch(request, { env, clientAddress: meta.clientAddress }),",
    "  { trustProxy, bodySizeLimit },",
    ");",
    "",
    // A same-origin image source is whatever the process would serve at that
    // path: a built asset, else the site as an anonymous GET.
    "const images = createImageLayer(config.imageDelivery, {",
    "  assets,",
    "  trustProxy,",
    "  basePath: config.basePath,",
    "  fetch: (request, meta) => site.fetch(request, { env, clientAddress: meta.clientAddress }),",
    "});",
    "",
    "/**",
    " * Start firing this site's scheduled tasks, returning a handle whose",
    " * `stop()` waits for the run in flight. Called for you when this module is",
    " * run directly; an embedder calls it when it wants cron, so importing the",
    " * module starts no background work on its own.",
    " */",
    "export async function startCron(overrides = {}) {",
    "  const app = await appPromise;",
    "  handler ??= config.runtime.createHandler(app);",
    "  return startScheduledRunner({",
    "    app,",
    "    env,",
    "    fire: (cron, scheduledTime) => site.scheduled({ scheduledTime, cron }, { env }),",
    "    ...overrides,",
    "  });",
    "}",
    "",
    "/** Connect-style listener for embedding: the built assets first, then image transforms, then the site, which answers every request. */",
    "export function listener(req, res) {",
    "  assets.serve(req, res, () => images.serve(req, res, () => bridge(req, res)));",
    "}",
    "",
    "if (import.meta.main) {",
    '  const port = Number(process.env.PORT || "3000");',
    '  const host = process.env.HOST || "0.0.0.0";',
    "  const server = createServer(listener);",
    "  server.listen(port, host, () => {",
    "    console.log(`plumix: listening on http://${host}:${server.address().port}`);",
    "  });",
    "",
    // Scheduled tasks are the site's own work, so they run wherever the site
    // runs; `cron: false` hands them to an external scheduler instead. Started
    // after `listen` and never awaited by it: building the app must not delay
    // serving, and a scheduler that cannot start must not take down a process
    // that is already answering requests.
    "  let cron;",
    "  let stopping = false;",
    "  if (config.runtime.config.cron !== false) {",
    "    startCron().then(",
    // A signal can land while `buildApp` is still running. Without this the
    // scheduler would start behind the shutdown and fire into its drain.
    "      (started) => { cron = started; if (stopping) void started.stop({ timeoutMs: 0 }); },",
    '      (error) => { console.error("plumix: cron failed to start", error); },',
    "    );",
    "  }",
    "",
    // Stop accepting; in-flight responses get the deadline first, then the
    // deferred work they leave behind gets what remains; whatever is still
    // open is cut. Both listeners come off, so a second signal of either
    // kind falls to Node's default and exits at once.
    "  const shutdown = (signal) => {",
    '    process.off("SIGTERM", shutdown);',
    '    process.off("SIGINT", shutdown);',
    "    console.log(`plumix: ${signal} received, draining`);",
    `    const deadline = Date.now() + ${DRAIN_DEADLINE_MS};`,
    "    const closed = new Promise((resolve) => server.close(() => resolve(true)));",
    "    server.closeIdleConnections();",
    "    void (async () => {",
    // Before the drain, not during it: `dispose()` waits for deferred work,
    // and a firing that started behind it would hand it more. Bounded by the
    // same budget the drain then spends, so a long task cannot hold the whole
    // shutdown open and leave `dispose()` nothing.
    "      stopping = true;",
    "      await cron?.stop({ timeoutMs: Math.max(0, deadline - Date.now()) });",
    `      const finished = await Promise.race([closed, sleep(${DRAIN_DEADLINE_MS}, false)]);`,
    "      const { abandoned } = handler",
    "        ? await handler.dispose({ timeoutMs: Math.max(0, deadline - Date.now()) })",
    "        : { abandoned: 0 };",
    "      server.closeAllConnections();",
    "      if (!finished) console.error(`plumix: exiting with in-flight responses cut after ${" +
      String(DRAIN_DEADLINE_MS) +
      "}ms`);",
    "      if (abandoned > 0) console.error(`plumix: exiting with ${abandoned} deferred task(s) abandoned`);",
    "      process.exit(!finished || abandoned > 0 ? 1 : 0);",
    "    })();",
    "  };",
    '  process.on("SIGTERM", shutdown);',
    '  process.on("SIGINT", shutdown);',
    "}",
    "",
  ];
  return lines.join("\n");
}
