import type { EntrySourceOptions } from "plumix";

import { ASSETS_DIR_ENV, DRAIN_DEADLINE_MS } from "./entry-constants.js";

/**
 * The Node entry: the portable `{ fetch, scheduled }` default export, a
 * Connect-style `listener` for embedding, and — only when run directly — an
 * `http` server in front of it.
 */
export function generateEntry({ configModule }: EntrySourceOptions): string {
  const lines = [
    "// Generated by plumix — do not edit.",
    "// Regenerated from plumix.config.ts on each build.",
    "",
    'import { createServer } from "node:http";',
    'import { dirname, resolve } from "node:path";',
    'import { setTimeout as sleep } from "node:timers/promises";',
    'import { fileURLToPath } from "node:url";',
    'import { buildApp, renderDevBootErrorResponse } from "plumix";',
    'import { createAssetsLayer, createRequestListener } from "@plumix/runtime-node";',
    // The plumix Vite plugin resolves this: `{}` in dev, the client's
    // `.vite/manifest.json` in a build, so SSR can inject the hashed
    // stylesheet links.
    'import assetManifest from "virtual:plumix/asset-manifest";',
    `import config from ${JSON.stringify(configModule)};`,
    "",
    'export * from "virtual:plumix/worker-exports";',
    "",
    // Read once, at start. The assets directory is named on it so the handler
    // serves `dist/client` beside this module, the way Cloudflare's handler
    // reads `env.ASSETS`.
    "const env = {",
    "  ...process.env,",
    `  ${ASSETS_DIR_ENV}: resolve(dirname(fileURLToPath(import.meta.url)), "../client"),`,
    "};",
    "",
    "const appPromise = buildApp(config, {",
    "  assetManifest,",
    "});",
    "let handler;",
    "",
    "const site = {",
    "  async fetch(request, invocation = { env }) {",
    "    let app;",
    "    try {",
    "      app = await appPromise;",
    "    } catch (bootError) {",
    // Dev-only, statically false in a build so the branch and the renderer
    // tree-shake out; see the Cloudflare entry.
    "      if (process.env.PLUMIX_DEV) {",
    "        return renderDevBootErrorResponse(bootError);",
    "      }",
    "      throw bootError;",
    "    }",
    "    handler ??= config.runtime.createHandler(app);",
    "    return handler.fetch(request, invocation);",
    "  },",
    "  async scheduled(event, invocation = { env }) {",
    "    const app = await appPromise;",
    "    handler ??= config.runtime.createHandler(app);",
    "    if (handler.scheduled) await handler.scheduled(event, invocation);",
    "  },",
    "};",
    "",
    "export default site;",
    "",
    "const { trustProxy, bodySizeLimit } = config.runtime.config;",
    `const assets = createAssetsLayer({ root: env.${ASSETS_DIR_ENV} });`,
    "const bridge = createRequestListener(",
    "  (request, meta) => site.fetch(request, { env, clientAddress: meta.clientAddress }),",
    "  { trustProxy, bodySizeLimit },",
    ");",
    "",
    "/** Connect-style listener for embedding: the built assets first, then the site, which answers every request. */",
    "export function listener(req, res) {",
    "  assets.serve(req, res, () => bridge(req, res));",
    "}",
    "",
    "if (import.meta.main) {",
    '  const port = Number(process.env.PORT || "3000");',
    '  const host = process.env.HOST || "0.0.0.0";',
    "  const server = createServer(listener);",
    "  server.listen(port, host, () => {",
    "    console.log(`plumix: listening on http://${host}:${server.address().port}`);",
    "  });",
    "",
    // Stop accepting; in-flight responses get the deadline first, then the
    // deferred work they leave behind gets what remains; whatever is still
    // open is cut. Both listeners come off, so a second signal of either
    // kind falls to Node's default and exits at once.
    "  const shutdown = (signal) => {",
    '    process.off("SIGTERM", shutdown);',
    '    process.off("SIGINT", shutdown);',
    "    console.log(`plumix: ${signal} received, draining`);",
    `    const deadline = Date.now() + ${DRAIN_DEADLINE_MS};`,
    "    const closed = new Promise((resolve) => server.close(() => resolve(true)));",
    "    server.closeIdleConnections();",
    "    void (async () => {",
    `      const finished = await Promise.race([closed, sleep(${DRAIN_DEADLINE_MS}, false)]);`,
    "      const { abandoned } = handler",
    "        ? await handler.dispose({ timeoutMs: Math.max(0, deadline - Date.now()) })",
    "        : { abandoned: 0 };",
    "      server.closeAllConnections();",
    "      if (!finished) console.error(`plumix: exiting with in-flight responses cut after ${" +
      String(DRAIN_DEADLINE_MS) +
      "}ms`);",
    "      if (abandoned > 0) console.error(`plumix: exiting with ${abandoned} deferred task(s) abandoned`);",
    "      process.exit(!finished || abandoned > 0 ? 1 : 0);",
    "    })();",
    "  };",
    '  process.on("SIGTERM", shutdown);',
    '  process.on("SIGINT", shutdown);',
    "}",
    "",
  ];
  return lines.join("\n");
}
